window.routesIndex = {
  "version": "20260517-2232",
  "city_id": "cincinnati",
  "routes": [
    {
      "route_id": "bcrta_5620",
      "direction_id": 0,
      "file": "route-bcrta_5620-dir0.json",
      "route_type": "3",
      "route_short_name": "BL",
      "route_long_name": "Blue Line",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route BL - Outbound"
    },
    {
      "route_id": "bcrta_5632",
      "direction_id": 0,
      "file": "route-bcrta_5632-dir0.json",
      "route_type": "3",
      "route_short_name": "GL",
      "route_long_name": "Gold Line",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route GL - Outbound"
    },
    {
      "route_id": "bcrta_5633",
      "direction_id": 0,
      "file": "route-bcrta_5633-dir0.json",
      "route_type": "3",
      "route_short_name": "GRL",
      "route_long_name": "Green Line",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route GRL - Outbound"
    },
    {
      "route_id": "bcrta_5635",
      "direction_id": 0,
      "file": "route-bcrta_5635-dir0.json",
      "route_type": "3",
      "route_short_name": "R1",
      "route_long_name": "R1 - Hamilton/Middletown Shuttle",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route R1 - Outbound"
    },
    {
      "route_id": "bcrta_5635",
      "direction_id": 1,
      "file": "route-bcrta_5635-dir1.json",
      "route_type": "3",
      "route_short_name": "R1",
      "route_long_name": "R1 - Hamilton/Middletown Shuttle",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route R1 - Inbound"
    },
    {
      "route_id": "bcrta_5636",
      "direction_id": 0,
      "file": "route-bcrta_5636-dir0.json",
      "route_type": "3",
      "route_short_name": "RL",
      "route_long_name": "Red Line",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route RL - Outbound"
    },
    {
      "route_id": "bcrta_5638",
      "direction_id": 0,
      "file": "route-bcrta_5638-dir0.json",
      "route_type": "3",
      "route_short_name": "R3",
      "route_long_name": "R3 - Oxford-Forest Park Connector",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route R3 - Outbound"
    },
    {
      "route_id": "bcrta_5638",
      "direction_id": 1,
      "file": "route-bcrta_5638-dir1.json",
      "route_type": "3",
      "route_short_name": "R3",
      "route_long_name": "R3 - Oxford-Forest Park Connector",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route R3 - Inbound"
    },
    {
      "route_id": "bcrta_5640",
      "direction_id": 0,
      "file": "route-bcrta_5640-dir0.json",
      "route_type": "3",
      "route_short_name": "R6",
      "route_long_name": "R6 - Job Connector",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route R6 - Outbound"
    },
    {
      "route_id": "bcrta_5640",
      "direction_id": 1,
      "file": "route-bcrta_5640-dir1.json",
      "route_type": "3",
      "route_short_name": "R6",
      "route_long_name": "R6 - Job Connector",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route R6 - Inbound"
    },
    {
      "route_id": "bcrta_6067",
      "direction_id": 0,
      "file": "route-bcrta_6067-dir0.json",
      "route_type": "3",
      "route_short_name": "CL",
      "route_long_name": "CincyLink",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route CL - Outbound"
    },
    {
      "route_id": "bcrta_6067",
      "direction_id": 1,
      "file": "route-bcrta_6067-dir1.json",
      "route_type": "3",
      "route_short_name": "CL",
      "route_long_name": "CincyLink",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route CL - Inbound"
    },
    {
      "route_id": "bcrta_6734",
      "direction_id": 0,
      "file": "route-bcrta_6734-dir0.json",
      "route_type": "3",
      "route_short_name": "CLX",
      "route_long_name": "CincyLink Express",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route CLX - Outbound"
    },
    {
      "route_id": "bcrta_6734",
      "direction_id": 1,
      "file": "route-bcrta_6734-dir1.json",
      "route_type": "3",
      "route_short_name": "CLX",
      "route_long_name": "CincyLink Express",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route CLX - Inbound"
    },
    {
      "route_id": "bcrta_6750",
      "direction_id": 0,
      "file": "route-bcrta_6750-dir0.json",
      "route_type": "3",
      "route_short_name": "O1",
      "route_long_name": "O1",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route O1 - Outbound"
    },
    {
      "route_id": "bcrta_6750",
      "direction_id": 1,
      "file": "route-bcrta_6750-dir1.json",
      "route_type": "3",
      "route_short_name": "O1",
      "route_long_name": "O1",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route O1 - Inbound"
    },
    {
      "route_id": "bcrta_6752",
      "direction_id": 0,
      "file": "route-bcrta_6752-dir0.json",
      "route_type": "3",
      "route_short_name": "O2",
      "route_long_name": "O2",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route O2 - Outbound"
    },
    {
      "route_id": "bcrta_6752",
      "direction_id": 1,
      "file": "route-bcrta_6752-dir1.json",
      "route_type": "3",
      "route_short_name": "O2",
      "route_long_name": "O2",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route O2 - Inbound"
    },
    {
      "route_id": "bcrta_6753",
      "direction_id": 0,
      "file": "route-bcrta_6753-dir0.json",
      "route_type": "3",
      "route_short_name": "O3",
      "route_long_name": "O3",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route O3 - Outbound"
    },
    {
      "route_id": "bcrta_6753",
      "direction_id": 1,
      "file": "route-bcrta_6753-dir1.json",
      "route_type": "3",
      "route_short_name": "O3",
      "route_long_name": "O3",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route O3 - Inbound"
    },
    {
      "route_id": "bcrta_6754",
      "direction_id": 0,
      "file": "route-bcrta_6754-dir0.json",
      "route_type": "3",
      "route_short_name": "O4",
      "route_long_name": "O4",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route O4 - Outbound"
    },
    {
      "route_id": "bcrta_6754",
      "direction_id": 1,
      "file": "route-bcrta_6754-dir1.json",
      "route_type": "3",
      "route_short_name": "O4",
      "route_long_name": "O4",
      "agency_id": "222",
      "direction_name": "Inbound",
      "route_title": "Route O4 - Inbound"
    },
    {
      "route_id": "bcrta_7048",
      "direction_id": 0,
      "file": "route-bcrta_7048-dir0.json",
      "route_type": "3",
      "route_short_name": "Miami Flyer PR",
      "route_long_name": "Miami Flyer Park and Ride",
      "agency_id": "222",
      "direction_name": "Outbound",
      "route_title": "Route Miami Flyer PR - Outbound"
    },
    {
      "route_id": "sorta_1",
      "direction_id": 0,
      "file": "route-sorta_1-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Mt. Adams",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 1 - Mt. Adams (Outbound)"
    },
    {
      "route_id": "sorta_1",
      "direction_id": 1,
      "file": "route-sorta_1-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Mt. Adams",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 1 - Mt. Adams (Inbound)"
    },
    {
      "route_id": "sorta_10",
      "direction_id": 0,
      "file": "route-sorta_10-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Madison Rd/ Erie Ave",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 10 - Madison Rd/ Erie Ave (Outbound)"
    },
    {
      "route_id": "sorta_10",
      "direction_id": 1,
      "file": "route-sorta_10-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Madison Rd/ Erie Ave",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 10 - Madison Rd/ Erie Ave (Inbound)"
    },
    {
      "route_id": "sorta_100",
      "direction_id": 0,
      "file": "route-sorta_100-dir0.json",
      "route_type": "0",
      "route_short_name": "100",
      "route_long_name": "Streetcar - OTR - Banks",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 100 - Streetcar - OTR - Banks (Outbound)"
    },
    {
      "route_id": "sorta_11",
      "direction_id": 0,
      "file": "route-sorta_11-dir0.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Madison Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 11 - Madison Road (Outbound)"
    },
    {
      "route_id": "sorta_11",
      "direction_id": 1,
      "file": "route-sorta_11-dir1.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Madison Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 11 - Madison Road (Inbound)"
    },
    {
      "route_id": "sorta_12",
      "direction_id": 0,
      "file": "route-sorta_12-dir0.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Madisonville Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 12 - Madisonville Commuter (Outbound)"
    },
    {
      "route_id": "sorta_12",
      "direction_id": 1,
      "file": "route-sorta_12-dir1.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Madisonville Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 12 - Madisonville Commuter (Inbound)"
    },
    {
      "route_id": "sorta_16",
      "direction_id": 0,
      "file": "route-sorta_16-dir0.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Spring Grove / Daly",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 16 - Spring Grove / Daly (Outbound)"
    },
    {
      "route_id": "sorta_16",
      "direction_id": 1,
      "file": "route-sorta_16-dir1.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Spring Grove / Daly",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 16 - Spring Grove / Daly (Inbound)"
    },
    {
      "route_id": "sorta_17",
      "direction_id": 0,
      "file": "route-sorta_17-dir0.json",
      "route_type": "3",
      "route_short_name": "17",
      "route_long_name": "Hamilton Avenue",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 17 - Hamilton Avenue (Outbound)"
    },
    {
      "route_id": "sorta_17",
      "direction_id": 1,
      "file": "route-sorta_17-dir1.json",
      "route_type": "3",
      "route_short_name": "17",
      "route_long_name": "Hamilton Avenue",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 17 - Hamilton Avenue (Inbound)"
    },
    {
      "route_id": "sorta_19",
      "direction_id": 0,
      "file": "route-sorta_19-dir0.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "Colerain Avenue",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 19 - Colerain Avenue (Outbound)"
    },
    {
      "route_id": "sorta_19",
      "direction_id": 1,
      "file": "route-sorta_19-dir1.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "Colerain Avenue",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 19 - Colerain Avenue (Inbound)"
    },
    {
      "route_id": "sorta_2",
      "direction_id": 0,
      "file": "route-sorta_2-dir0.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Madeira Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 2 - Madeira Commuter (Outbound)"
    },
    {
      "route_id": "sorta_2",
      "direction_id": 1,
      "file": "route-sorta_2-dir1.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Madeira Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 2 - Madeira Commuter (Inbound)"
    },
    {
      "route_id": "sorta_20",
      "direction_id": 0,
      "file": "route-sorta_20-dir0.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Winton Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 20 - Winton Road (Outbound)"
    },
    {
      "route_id": "sorta_20",
      "direction_id": 1,
      "file": "route-sorta_20-dir1.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Winton Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 20 - Winton Road (Inbound)"
    },
    {
      "route_id": "sorta_21",
      "direction_id": 0,
      "file": "route-sorta_21-dir0.json",
      "route_type": "3",
      "route_short_name": "21",
      "route_long_name": "Harrison Avenue",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 21 - Harrison Avenue (Outbound)"
    },
    {
      "route_id": "sorta_21",
      "direction_id": 1,
      "file": "route-sorta_21-dir1.json",
      "route_type": "3",
      "route_short_name": "21",
      "route_long_name": "Harrison Avenue",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 21 - Harrison Avenue (Inbound)"
    },
    {
      "route_id": "sorta_22",
      "direction_id": 0,
      "file": "route-sorta_22-dir0.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Glenway / Madison",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 22 - Glenway / Madison (Outbound)"
    },
    {
      "route_id": "sorta_22",
      "direction_id": 1,
      "file": "route-sorta_22-dir1.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Glenway / Madison",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 22 - Glenway / Madison (Inbound)"
    },
    {
      "route_id": "sorta_23",
      "direction_id": 0,
      "file": "route-sorta_23-dir0.json",
      "route_type": "3",
      "route_short_name": "23X",
      "route_long_name": "Forest Park Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 23X - Forest Park Express (Outbound)"
    },
    {
      "route_id": "sorta_23",
      "direction_id": 1,
      "file": "route-sorta_23-dir1.json",
      "route_type": "3",
      "route_short_name": "23X",
      "route_long_name": "Forest Park Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 23X - Forest Park Express (Inbound)"
    },
    {
      "route_id": "sorta_24",
      "direction_id": 0,
      "file": "route-sorta_24-dir0.json",
      "route_type": "3",
      "route_short_name": "24",
      "route_long_name": "MLK / Beechmont",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 24 - MLK / Beechmont (Outbound)"
    },
    {
      "route_id": "sorta_24",
      "direction_id": 1,
      "file": "route-sorta_24-dir1.json",
      "route_type": "3",
      "route_short_name": "24",
      "route_long_name": "MLK / Beechmont",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 24 - MLK / Beechmont (Inbound)"
    },
    {
      "route_id": "sorta_25",
      "direction_id": 0,
      "file": "route-sorta_25-dir0.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Mt. Lookout Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 25 - Mt. Lookout Commuter (Outbound)"
    },
    {
      "route_id": "sorta_25",
      "direction_id": 1,
      "file": "route-sorta_25-dir1.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Mt. Lookout Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 25 - Mt. Lookout Commuter (Inbound)"
    },
    {
      "route_id": "sorta_27",
      "direction_id": 0,
      "file": "route-sorta_27-dir0.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "Beekman / Linn",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 27 - Beekman / Linn (Outbound)"
    },
    {
      "route_id": "sorta_27",
      "direction_id": 1,
      "file": "route-sorta_27-dir1.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "Beekman / Linn",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 27 - Beekman / Linn (Inbound)"
    },
    {
      "route_id": "sorta_28",
      "direction_id": 0,
      "file": "route-sorta_28-dir0.json",
      "route_type": "3",
      "route_short_name": "28",
      "route_long_name": "East End",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 28 - East End (Outbound)"
    },
    {
      "route_id": "sorta_28",
      "direction_id": 1,
      "file": "route-sorta_28-dir1.json",
      "route_type": "3",
      "route_short_name": "28",
      "route_long_name": "East End",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 28 - East End (Inbound)"
    },
    {
      "route_id": "sorta_29",
      "direction_id": 0,
      "file": "route-sorta_29-dir0.json",
      "route_type": "3",
      "route_short_name": "29X",
      "route_long_name": "Milford Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 29X - Milford Express (Outbound)"
    },
    {
      "route_id": "sorta_29",
      "direction_id": 1,
      "file": "route-sorta_29-dir1.json",
      "route_type": "3",
      "route_short_name": "29X",
      "route_long_name": "Milford Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 29X - Milford Express (Inbound)"
    },
    {
      "route_id": "sorta_3",
      "direction_id": 0,
      "file": "route-sorta_3-dir0.json",
      "route_type": "3",
      "route_short_name": "3X",
      "route_long_name": "Montgomery Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 3X - Montgomery Express (Outbound)"
    },
    {
      "route_id": "sorta_3",
      "direction_id": 1,
      "file": "route-sorta_3-dir1.json",
      "route_type": "3",
      "route_short_name": "3X",
      "route_long_name": "Montgomery Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 3X - Montgomery Express (Inbound)"
    },
    {
      "route_id": "sorta_30",
      "direction_id": 0,
      "file": "route-sorta_30-dir0.json",
      "route_type": "3",
      "route_short_name": "30",
      "route_long_name": "Beechmont Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 30 - Beechmont Commuter (Outbound)"
    },
    {
      "route_id": "sorta_30",
      "direction_id": 1,
      "file": "route-sorta_30-dir1.json",
      "route_type": "3",
      "route_short_name": "30",
      "route_long_name": "Beechmont Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 30 - Beechmont Commuter (Inbound)"
    },
    {
      "route_id": "sorta_31",
      "direction_id": 0,
      "file": "route-sorta_31-dir0.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Taft / McMillan",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 31 - Taft / McMillan (Outbound)"
    },
    {
      "route_id": "sorta_31",
      "direction_id": 1,
      "file": "route-sorta_31-dir1.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Taft / McMillan",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 31 - Taft / McMillan (Inbound)"
    },
    {
      "route_id": "sorta_32",
      "direction_id": 0,
      "file": "route-sorta_32-dir0.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "West 8th Street",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 32 - West 8th Street (Outbound)"
    },
    {
      "route_id": "sorta_32",
      "direction_id": 1,
      "file": "route-sorta_32-dir1.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "West 8th Street",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 32 - West 8th Street (Inbound)"
    },
    {
      "route_id": "sorta_33",
      "direction_id": 0,
      "file": "route-sorta_33-dir0.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "Glenway Avenue",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 33 - Glenway Avenue (Outbound)"
    },
    {
      "route_id": "sorta_33",
      "direction_id": 1,
      "file": "route-sorta_33-dir1.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "Glenway Avenue",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 33 - Glenway Avenue (Inbound)"
    },
    {
      "route_id": "sorta_36",
      "direction_id": 0,
      "file": "route-sorta_36-dir0.json",
      "route_type": "3",
      "route_short_name": "36",
      "route_long_name": "Price Hill / Uptown",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 36 - Price Hill / Uptown (Outbound)"
    },
    {
      "route_id": "sorta_36",
      "direction_id": 1,
      "file": "route-sorta_36-dir1.json",
      "route_type": "3",
      "route_short_name": "36",
      "route_long_name": "Price Hill / Uptown",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 36 - Price Hill / Uptown (Inbound)"
    },
    {
      "route_id": "sorta_37",
      "direction_id": 0,
      "file": "route-sorta_37-dir0.json",
      "route_type": "3",
      "route_short_name": "37",
      "route_long_name": "MLK / Westwood Northern",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 37 - MLK / Westwood Northern (Outbound)"
    },
    {
      "route_id": "sorta_37",
      "direction_id": 1,
      "file": "route-sorta_37-dir1.json",
      "route_type": "3",
      "route_short_name": "37",
      "route_long_name": "MLK / Westwood Northern",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 37 - MLK / Westwood Northern (Inbound)"
    },
    {
      "route_id": "sorta_38",
      "direction_id": 0,
      "file": "route-sorta_38-dir0.json",
      "route_type": "3",
      "route_short_name": "38",
      "route_long_name": "Uptown Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 38 - Uptown Commuter (Outbound)"
    },
    {
      "route_id": "sorta_38",
      "direction_id": 1,
      "file": "route-sorta_38-dir1.json",
      "route_type": "3",
      "route_short_name": "38",
      "route_long_name": "Uptown Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 38 - Uptown Commuter (Inbound)"
    },
    {
      "route_id": "sorta_4",
      "direction_id": 0,
      "file": "route-sorta_4-dir0.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "Montgomery Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 4 - Montgomery Road (Outbound)"
    },
    {
      "route_id": "sorta_4",
      "direction_id": 1,
      "file": "route-sorta_4-dir1.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "Montgomery Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 4 - Montgomery Road (Inbound)"
    },
    {
      "route_id": "sorta_40",
      "direction_id": 0,
      "file": "route-sorta_40-dir0.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Montana Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 40 - Montana Commuter (Outbound)"
    },
    {
      "route_id": "sorta_40",
      "direction_id": 1,
      "file": "route-sorta_40-dir1.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Montana Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 40 - Montana Commuter (Inbound)"
    },
    {
      "route_id": "sorta_41",
      "direction_id": 0,
      "file": "route-sorta_41-dir0.json",
      "route_type": "3",
      "route_short_name": "41",
      "route_long_name": "North Bend Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 41 - North Bend Road (Outbound)"
    },
    {
      "route_id": "sorta_41",
      "direction_id": 1,
      "file": "route-sorta_41-dir1.json",
      "route_type": "3",
      "route_short_name": "41",
      "route_long_name": "North Bend Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 41 - North Bend Road (Inbound)"
    },
    {
      "route_id": "sorta_43",
      "direction_id": 0,
      "file": "route-sorta_43-dir0.json",
      "route_type": "3",
      "route_short_name": "43",
      "route_long_name": "Reading Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 43 - Reading Road (Outbound)"
    },
    {
      "route_id": "sorta_43",
      "direction_id": 1,
      "file": "route-sorta_43-dir1.json",
      "route_type": "3",
      "route_short_name": "43",
      "route_long_name": "Reading Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 43 - Reading Road (Inbound)"
    },
    {
      "route_id": "sorta_46",
      "direction_id": 0,
      "file": "route-sorta_46-dir0.json",
      "route_type": "3",
      "route_short_name": "46",
      "route_long_name": "Avondale",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 46 - Avondale (Outbound)"
    },
    {
      "route_id": "sorta_46",
      "direction_id": 1,
      "file": "route-sorta_46-dir1.json",
      "route_type": "3",
      "route_short_name": "46",
      "route_long_name": "Avondale",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 46 - Avondale (Inbound)"
    },
    {
      "route_id": "sorta_49",
      "direction_id": 0,
      "file": "route-sorta_49-dir0.json",
      "route_type": "3",
      "route_short_name": "49",
      "route_long_name": "Fairmount",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 49 - Fairmount (Outbound)"
    },
    {
      "route_id": "sorta_49",
      "direction_id": 1,
      "file": "route-sorta_49-dir1.json",
      "route_type": "3",
      "route_short_name": "49",
      "route_long_name": "Fairmount",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 49 - Fairmount (Inbound)"
    },
    {
      "route_id": "sorta_5",
      "direction_id": 0,
      "file": "route-sorta_5-dir0.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Blue Ash",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 5 - Blue Ash (Outbound)"
    },
    {
      "route_id": "sorta_5",
      "direction_id": 1,
      "file": "route-sorta_5-dir1.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Blue Ash",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 5 - Blue Ash (Inbound)"
    },
    {
      "route_id": "sorta_50",
      "direction_id": 0,
      "file": "route-sorta_50-dir0.json",
      "route_type": "3",
      "route_short_name": "50",
      "route_long_name": "River Road Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 50 - River Road Commuter (Outbound)"
    },
    {
      "route_id": "sorta_50",
      "direction_id": 1,
      "file": "route-sorta_50-dir1.json",
      "route_type": "3",
      "route_short_name": "50",
      "route_long_name": "River Road Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 50 - River Road Commuter (Inbound)"
    },
    {
      "route_id": "sorta_51",
      "direction_id": 0,
      "file": "route-sorta_51-dir0.json",
      "route_type": "3",
      "route_short_name": "51",
      "route_long_name": "Uptown Connector",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 51 - Uptown Connector (Outbound)"
    },
    {
      "route_id": "sorta_51",
      "direction_id": 1,
      "file": "route-sorta_51-dir1.json",
      "route_type": "3",
      "route_short_name": "51",
      "route_long_name": "Uptown Connector",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 51 - Uptown Connector (Inbound)"
    },
    {
      "route_id": "sorta_52",
      "direction_id": 0,
      "file": "route-sorta_52-dir0.json",
      "route_type": "3",
      "route_short_name": "52X",
      "route_long_name": "Harrison Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 52X - Harrison Express (Outbound)"
    },
    {
      "route_id": "sorta_52",
      "direction_id": 1,
      "file": "route-sorta_52-dir1.json",
      "route_type": "3",
      "route_short_name": "52X",
      "route_long_name": "Harrison Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 52X - Harrison Express (Inbound)"
    },
    {
      "route_id": "sorta_6",
      "direction_id": 0,
      "file": "route-sorta_6-dir0.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "Queen City Avenue",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 6 - Queen City Avenue (Outbound)"
    },
    {
      "route_id": "sorta_6",
      "direction_id": 1,
      "file": "route-sorta_6-dir1.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "Queen City Avenue",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 6 - Queen City Avenue (Inbound)"
    },
    {
      "route_id": "sorta_61",
      "direction_id": 0,
      "file": "route-sorta_61-dir0.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "Galbraith Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 61 - Galbraith Road (Outbound)"
    },
    {
      "route_id": "sorta_61",
      "direction_id": 1,
      "file": "route-sorta_61-dir1.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "Galbraith Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 61 - Galbraith Road (Inbound)"
    },
    {
      "route_id": "sorta_64",
      "direction_id": 0,
      "file": "route-sorta_64-dir0.json",
      "route_type": "3",
      "route_short_name": "64",
      "route_long_name": "Westwood",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 64 - Westwood (Outbound)"
    },
    {
      "route_id": "sorta_64",
      "direction_id": 1,
      "file": "route-sorta_64-dir1.json",
      "route_type": "3",
      "route_short_name": "64",
      "route_long_name": "Westwood",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 64 - Westwood (Inbound)"
    },
    {
      "route_id": "sorta_65",
      "direction_id": 0,
      "file": "route-sorta_65-dir0.json",
      "route_type": "3",
      "route_short_name": "65",
      "route_long_name": "Western Hills",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 65 - Western Hills (Outbound)"
    },
    {
      "route_id": "sorta_65",
      "direction_id": 1,
      "file": "route-sorta_65-dir1.json",
      "route_type": "3",
      "route_short_name": "65",
      "route_long_name": "Western Hills",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 65 - Western Hills (Inbound)"
    },
    {
      "route_id": "sorta_67",
      "direction_id": 0,
      "file": "route-sorta_67-dir0.json",
      "route_type": "3",
      "route_short_name": "67",
      "route_long_name": "Kemper Road",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 67 - Kemper Road (Outbound)"
    },
    {
      "route_id": "sorta_67",
      "direction_id": 1,
      "file": "route-sorta_67-dir1.json",
      "route_type": "3",
      "route_short_name": "67",
      "route_long_name": "Kemper Road",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 67 - Kemper Road (Inbound)"
    },
    {
      "route_id": "sorta_71",
      "direction_id": 0,
      "file": "route-sorta_71-dir0.json",
      "route_type": "3",
      "route_short_name": "71X",
      "route_long_name": "Kings Island Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 71X - Kings Island Express (Outbound)"
    },
    {
      "route_id": "sorta_71",
      "direction_id": 1,
      "file": "route-sorta_71-dir1.json",
      "route_type": "3",
      "route_short_name": "71X",
      "route_long_name": "Kings Island Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 71X - Kings Island Express (Inbound)"
    },
    {
      "route_id": "sorta_74",
      "direction_id": 0,
      "file": "route-sorta_74-dir0.json",
      "route_type": "3",
      "route_short_name": "74X",
      "route_long_name": "Colerain Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 74X - Colerain Express (Outbound)"
    },
    {
      "route_id": "sorta_74",
      "direction_id": 1,
      "file": "route-sorta_74-dir1.json",
      "route_type": "3",
      "route_short_name": "74X",
      "route_long_name": "Colerain Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 74X - Colerain Express (Inbound)"
    },
    {
      "route_id": "sorta_75",
      "direction_id": 0,
      "file": "route-sorta_75-dir0.json",
      "route_type": "3",
      "route_short_name": "75X",
      "route_long_name": "Anderson Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 75X - Anderson Express (Outbound)"
    },
    {
      "route_id": "sorta_75",
      "direction_id": 1,
      "file": "route-sorta_75-dir1.json",
      "route_type": "3",
      "route_short_name": "75X",
      "route_long_name": "Anderson Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 75X - Anderson Express (Inbound)"
    },
    {
      "route_id": "sorta_77",
      "direction_id": 0,
      "file": "route-sorta_77-dir0.json",
      "route_type": "3",
      "route_short_name": "77",
      "route_long_name": "Delhi",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 77 - Delhi (Outbound)"
    },
    {
      "route_id": "sorta_77",
      "direction_id": 1,
      "file": "route-sorta_77-dir1.json",
      "route_type": "3",
      "route_short_name": "77",
      "route_long_name": "Delhi",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 77 - Delhi (Inbound)"
    },
    {
      "route_id": "sorta_78",
      "direction_id": 0,
      "file": "route-sorta_78-dir0.json",
      "route_type": "3",
      "route_short_name": "78",
      "route_long_name": "Vine Street",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 78 - Vine Street (Outbound)"
    },
    {
      "route_id": "sorta_78",
      "direction_id": 1,
      "file": "route-sorta_78-dir1.json",
      "route_type": "3",
      "route_short_name": "78",
      "route_long_name": "Vine Street",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 78 - Vine Street (Inbound)"
    },
    {
      "route_id": "sorta_8",
      "direction_id": 0,
      "file": "route-sorta_8-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Blue Ash / Silverton Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 8 - Blue Ash / Silverton Commuter (Outbound)"
    },
    {
      "route_id": "sorta_8",
      "direction_id": 1,
      "file": "route-sorta_8-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Blue Ash / Silverton Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 8 - Blue Ash / Silverton Commuter (Inbound)"
    },
    {
      "route_id": "sorta_81",
      "direction_id": 0,
      "file": "route-sorta_81-dir0.json",
      "route_type": "3",
      "route_short_name": "81",
      "route_long_name": "Mt. Washington Commuter",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 81 - Mt. Washington Commuter (Outbound)"
    },
    {
      "route_id": "sorta_81",
      "direction_id": 1,
      "file": "route-sorta_81-dir1.json",
      "route_type": "3",
      "route_short_name": "81",
      "route_long_name": "Mt. Washington Commuter",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 81 - Mt. Washington Commuter (Inbound)"
    },
    {
      "route_id": "sorta_82",
      "direction_id": 0,
      "file": "route-sorta_82-dir0.json",
      "route_type": "3",
      "route_short_name": "82X",
      "route_long_name": "Eastgate Express",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] 82X - Eastgate Express (Outbound)"
    },
    {
      "route_id": "sorta_82",
      "direction_id": 1,
      "file": "route-sorta_82-dir1.json",
      "route_type": "3",
      "route_short_name": "82X",
      "route_long_name": "Eastgate Express",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] 82X - Eastgate Express (Inbound)"
    },
    {
      "route_id": "sorta_90",
      "direction_id": 0,
      "file": "route-sorta_90-dir0.json",
      "route_type": "3",
      "route_short_name": "M+",
      "route_long_name": "MetroPlus",
      "agency_id": "nan",
      "direction_name": "Outbound",
      "route_title": "[SORTA] M+ - MetroPlus (Outbound)"
    },
    {
      "route_id": "sorta_90",
      "direction_id": 1,
      "file": "route-sorta_90-dir1.json",
      "route_type": "3",
      "route_short_name": "M+",
      "route_long_name": "MetroPlus",
      "agency_id": "nan",
      "direction_name": "Inbound",
      "route_title": "[SORTA] M+ - MetroPlus (Inbound)"
    },
    {
      "route_id": "tank_1",
      "direction_id": 0,
      "file": "route-tank_1-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Dixie Hwy/Florence",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 1 - Dixie Hwy/Florence (Outbound)"
    },
    {
      "route_id": "tank_1",
      "direction_id": 1,
      "file": "route-tank_1-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Dixie Hwy/Florence",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 1 - Dixie Hwy/Florence (Inbound)"
    },
    {
      "route_id": "tank_12",
      "direction_id": 0,
      "file": "route-tank_12-dir0.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Bellevue/Dayton",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 12 - Bellevue/Dayton (Outbound)"
    },
    {
      "route_id": "tank_12",
      "direction_id": 1,
      "file": "route-tank_12-dir1.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Bellevue/Dayton",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 12 - Bellevue/Dayton (Inbound)"
    },
    {
      "route_id": "tank_16",
      "direction_id": 0,
      "file": "route-tank_16-dir0.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "West Newport/Fort Thomas",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 16 - West Newport/Fort Thomas (Outbound)"
    },
    {
      "route_id": "tank_16",
      "direction_id": 1,
      "file": "route-tank_16-dir1.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "West Newport/Fort Thomas",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 16 - West Newport/Fort Thomas (Inbound)"
    },
    {
      "route_id": "tank_201",
      "direction_id": 0,
      "file": "route-tank_201-dir0.json",
      "route_type": "3",
      "route_short_name": "2X",
      "route_long_name": "Airporter",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 2X - Airporter (Outbound)"
    },
    {
      "route_id": "tank_201",
      "direction_id": 1,
      "file": "route-tank_201-dir1.json",
      "route_type": "3",
      "route_short_name": "2X",
      "route_long_name": "Airporter",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 2X - Airporter (Inbound)"
    },
    {
      "route_id": "tank_24",
      "direction_id": 1,
      "file": "route-tank_24-dir1.json",
      "route_type": "3",
      "route_short_name": "24",
      "route_long_name": "NKU Shuttle",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 24 - NKU Shuttle (Inbound)"
    },
    {
      "route_id": "tank_25",
      "direction_id": 0,
      "file": "route-tank_25-dir0.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "NKU/Alexandria",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 25 - NKU/Alexandria (Outbound)"
    },
    {
      "route_id": "tank_25",
      "direction_id": 1,
      "file": "route-tank_25-dir1.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "NKU/Alexandria",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 25 - NKU/Alexandria (Inbound)"
    },
    {
      "route_id": "tank_2501",
      "direction_id": 0,
      "file": "route-tank_2501-dir0.json",
      "route_type": "3",
      "route_short_name": "25X",
      "route_long_name": "Alexandria Express",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 25X - Alexandria Express (Outbound)"
    },
    {
      "route_id": "tank_2501",
      "direction_id": 1,
      "file": "route-tank_2501-dir1.json",
      "route_type": "3",
      "route_short_name": "25X",
      "route_long_name": "Alexandria Express",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 25X - Alexandria Express (Inbound)"
    },
    {
      "route_id": "tank_3",
      "direction_id": 0,
      "file": "route-tank_3-dir0.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Ludlow/Bromley",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 3 - Ludlow/Bromley (Outbound)"
    },
    {
      "route_id": "tank_3",
      "direction_id": 1,
      "file": "route-tank_3-dir1.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Ludlow/Bromley",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 3 - Ludlow/Bromley (Inbound)"
    },
    {
      "route_id": "tank_3001",
      "direction_id": 0,
      "file": "route-tank_3001-dir0.json",
      "route_type": "3",
      "route_short_name": "30X",
      "route_long_name": "Fort Wright/Lake Park Dr Express",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 30X - Fort Wright/Lake Park Dr Express (Outbound)"
    },
    {
      "route_id": "tank_3001",
      "direction_id": 1,
      "file": "route-tank_3001-dir1.json",
      "route_type": "3",
      "route_short_name": "30X",
      "route_long_name": "Fort Wright/Lake Park Dr Express",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 30X - Fort Wright/Lake Park Dr Express (Inbound)"
    },
    {
      "route_id": "tank_352",
      "direction_id": 0,
      "file": "route-tank_352-dir0.json",
      "route_type": "3",
      "route_short_name": "352",
      "route_long_name": "Holmes HS #3 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 352 - Holmes HS #3 PM (Outbound)"
    },
    {
      "route_id": "tank_3701",
      "direction_id": 0,
      "file": "route-tank_3701-dir0.json",
      "route_type": "3",
      "route_short_name": "3701",
      "route_long_name": "Southbank Shuttle",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 3701 - Southbank Shuttle (Outbound)"
    },
    {
      "route_id": "tank_3701",
      "direction_id": 1,
      "file": "route-tank_3701-dir1.json",
      "route_type": "3",
      "route_short_name": "3701",
      "route_long_name": "Southbank Shuttle",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 3701 - Southbank Shuttle (Inbound)"
    },
    {
      "route_id": "tank_3901",
      "direction_id": 0,
      "file": "route-tank_3901-dir0.json",
      "route_type": "3",
      "route_short_name": "39X",
      "route_long_name": "Petersburg Rd/South Hebron Express",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 39X - Petersburg Rd/South Hebron Express (Outbound)"
    },
    {
      "route_id": "tank_3901",
      "direction_id": 1,
      "file": "route-tank_3901-dir1.json",
      "route_type": "3",
      "route_short_name": "39X",
      "route_long_name": "Petersburg Rd/South Hebron Express",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 39X - Petersburg Rd/South Hebron Express (Inbound)"
    },
    {
      "route_id": "tank_4001",
      "direction_id": 0,
      "file": "route-tank_4001-dir0.json",
      "route_type": "3",
      "route_short_name": "40X",
      "route_long_name": "Worldwide Blvd/North Hebron Express",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 40X - Worldwide Blvd/North Hebron Express (Outbound)"
    },
    {
      "route_id": "tank_4001",
      "direction_id": 1,
      "file": "route-tank_4001-dir1.json",
      "route_type": "3",
      "route_short_name": "40X",
      "route_long_name": "Worldwide Blvd/North Hebron Express",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 40X - Worldwide Blvd/North Hebron Express (Inbound)"
    },
    {
      "route_id": "tank_4201",
      "direction_id": 0,
      "file": "route-tank_4201-dir0.json",
      "route_type": "3",
      "route_short_name": "42X",
      "route_long_name": "Florence Hub/Industrial Rd Express",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 42X - Florence Hub/Industrial Rd Express (Outbound)"
    },
    {
      "route_id": "tank_4201",
      "direction_id": 1,
      "file": "route-tank_4201-dir1.json",
      "route_type": "3",
      "route_short_name": "42X",
      "route_long_name": "Florence Hub/Industrial Rd Express",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 42X - Florence Hub/Industrial Rd Express (Inbound)"
    },
    {
      "route_id": "tank_450",
      "direction_id": 1,
      "file": "route-tank_450-dir1.json",
      "route_type": "3",
      "route_short_name": "450",
      "route_long_name": "Holmes HS #2 PM",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 450 - Holmes HS #2 PM (Inbound)"
    },
    {
      "route_id": "tank_451",
      "direction_id": 1,
      "file": "route-tank_451-dir1.json",
      "route_type": "3",
      "route_short_name": "451",
      "route_long_name": "Holmes HS #2 AM",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 451 - Holmes HS #2 AM (Inbound)"
    },
    {
      "route_id": "tank_485",
      "direction_id": 0,
      "file": "route-tank_485-dir0.json",
      "route_type": "3",
      "route_short_name": "485",
      "route_long_name": "Holmes HS #5 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 485 - Holmes HS #5 PM (Outbound)"
    },
    {
      "route_id": "tank_5",
      "direction_id": 0,
      "file": "route-tank_5-dir0.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Holman Ave/Fort Wright",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 5 - Holman Ave/Fort Wright (Outbound)"
    },
    {
      "route_id": "tank_5",
      "direction_id": 1,
      "file": "route-tank_5-dir1.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Holman Ave/Fort Wright",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 5 - Holman Ave/Fort Wright (Inbound)"
    },
    {
      "route_id": "tank_552",
      "direction_id": 1,
      "file": "route-tank_552-dir1.json",
      "route_type": "3",
      "route_short_name": "552",
      "route_long_name": "Holmes HS #1 AM",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 552 - Holmes HS #1 AM (Inbound)"
    },
    {
      "route_id": "tank_553",
      "direction_id": 0,
      "file": "route-tank_553-dir0.json",
      "route_type": "3",
      "route_short_name": "553",
      "route_long_name": "Holmes HS #6 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 553 - Holmes HS #6 PM (Outbound)"
    },
    {
      "route_id": "tank_64",
      "direction_id": 0,
      "file": "route-tank_64-dir0.json",
      "route_type": "3",
      "route_short_name": "64",
      "route_long_name": "64",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 64 - 64 (Outbound)"
    },
    {
      "route_id": "tank_64",
      "direction_id": 1,
      "file": "route-tank_64-dir1.json",
      "route_type": "3",
      "route_short_name": "64",
      "route_long_name": "64",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 64 - 64 (Inbound)"
    },
    {
      "route_id": "tank_652",
      "direction_id": 1,
      "file": "route-tank_652-dir1.json",
      "route_type": "3",
      "route_short_name": "652",
      "route_long_name": "Holmes HS #8 AM",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 652 - Holmes HS #8 AM (Inbound)"
    },
    {
      "route_id": "tank_7",
      "direction_id": 0,
      "file": "route-tank_7-dir0.json",
      "route_type": "3",
      "route_short_name": "7",
      "route_long_name": "Madison Ave/Latonia",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 7 - Madison Ave/Latonia (Outbound)"
    },
    {
      "route_id": "tank_7",
      "direction_id": 1,
      "file": "route-tank_7-dir1.json",
      "route_type": "3",
      "route_short_name": "7",
      "route_long_name": "Madison Ave/Latonia",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 7 - Madison Ave/Latonia (Inbound)"
    },
    {
      "route_id": "tank_751",
      "direction_id": 0,
      "file": "route-tank_751-dir0.json",
      "route_type": "3",
      "route_short_name": "751",
      "route_long_name": "Holmes HS #7 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 751 - Holmes HS #7 PM (Outbound)"
    },
    {
      "route_id": "tank_752",
      "direction_id": 0,
      "file": "route-tank_752-dir0.json",
      "route_type": "3",
      "route_short_name": "752",
      "route_long_name": "Holmes HS #9 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 752 - Holmes HS #9 PM (Outbound)"
    },
    {
      "route_id": "tank_8",
      "direction_id": 0,
      "file": "route-tank_8-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Eastern Ave/Crestview Hills",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 8 - Eastern Ave/Crestview Hills (Outbound)"
    },
    {
      "route_id": "tank_8",
      "direction_id": 1,
      "file": "route-tank_8-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Eastern Ave/Crestview Hills",
      "agency_id": "40019",
      "direction_name": "Inbound",
      "route_title": "[TANK] 8 - Eastern Ave/Crestview Hills (Inbound)"
    },
    {
      "route_id": "tank_851",
      "direction_id": 0,
      "file": "route-tank_851-dir0.json",
      "route_type": "3",
      "route_short_name": "851",
      "route_long_name": "Holmes HS #4 PM",
      "agency_id": "40019",
      "direction_name": "Outbound",
      "route_title": "[TANK] 851 - Holmes HS #4 PM (Outbound)"
    }
  ]
};
