window.routesIndex = {
  "version": "20260727-1437",
  "city_id": "cleveland",
  "routes": [
    {
      "route_id": "gcrta_1",
      "direction_id": 0,
      "file": "route-gcrta_1-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "St. Clair",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 1 - Outbound"
    },
    {
      "route_id": "gcrta_1",
      "direction_id": 1,
      "file": "route-gcrta_1-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "St. Clair",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 1 - Inbound"
    },
    {
      "route_id": "gcrta_10",
      "direction_id": 0,
      "file": "route-gcrta_10-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "East 105\u2013Lakeshore",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 10 - Outbound"
    },
    {
      "route_id": "gcrta_10",
      "direction_id": 1,
      "file": "route-gcrta_10-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "East 105\u2013Lakeshore",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 10 - Inbound"
    },
    {
      "route_id": "gcrta_11",
      "direction_id": 0,
      "file": "route-gcrta_11-dir0.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Quincy\u2013Cedar",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 11 - Outbound"
    },
    {
      "route_id": "gcrta_11",
      "direction_id": 1,
      "file": "route-gcrta_11-dir1.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Quincy\u2013Cedar",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 11 - Inbound"
    },
    {
      "route_id": "gcrta_14",
      "direction_id": 0,
      "file": "route-gcrta_14-dir0.json",
      "route_type": "3",
      "route_short_name": "14-14A",
      "route_long_name": "Kinsman",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 14-14A - Outbound"
    },
    {
      "route_id": "gcrta_14",
      "direction_id": 1,
      "file": "route-gcrta_14-dir1.json",
      "route_type": "3",
      "route_short_name": "14-14A",
      "route_long_name": "Kinsman",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 14-14A - Inbound"
    },
    {
      "route_id": "gcrta_15",
      "direction_id": 0,
      "file": "route-gcrta_15-dir0.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Union\u2013Harvard",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 15 - Outbound"
    },
    {
      "route_id": "gcrta_15",
      "direction_id": 1,
      "file": "route-gcrta_15-dir1.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Union\u2013Harvard",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 15 - Inbound"
    },
    {
      "route_id": "gcrta_16",
      "direction_id": 0,
      "file": "route-gcrta_16-dir0.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "East 55",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 16 - Outbound"
    },
    {
      "route_id": "gcrta_16",
      "direction_id": 1,
      "file": "route-gcrta_16-dir1.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "East 55",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 16 - Inbound"
    },
    {
      "route_id": "gcrta_18",
      "direction_id": 0,
      "file": "route-gcrta_18-dir0.json",
      "route_type": "3",
      "route_short_name": "18",
      "route_long_name": "West 98\u2013Garfield",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 18 - Outbound"
    },
    {
      "route_id": "gcrta_18",
      "direction_id": 1,
      "file": "route-gcrta_18-dir1.json",
      "route_type": "3",
      "route_short_name": "18",
      "route_long_name": "West 98\u2013Garfield",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 18 - Inbound"
    },
    {
      "route_id": "gcrta_19",
      "direction_id": 0,
      "file": "route-gcrta_19-dir0.json",
      "route_type": "3",
      "route_short_name": "19-19A-19B",
      "route_long_name": "Broadway",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 19-19A-19B - Outbound"
    },
    {
      "route_id": "gcrta_19",
      "direction_id": 1,
      "file": "route-gcrta_19-dir1.json",
      "route_type": "3",
      "route_short_name": "19-19A-19B",
      "route_long_name": "Broadway",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 19-19A-19B - Inbound"
    },
    {
      "route_id": "gcrta_2",
      "direction_id": 0,
      "file": "route-gcrta_2-dir0.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "East 79",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 2 - Outbound"
    },
    {
      "route_id": "gcrta_2",
      "direction_id": 1,
      "file": "route-gcrta_2-dir1.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "East 79",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 2 - Inbound"
    },
    {
      "route_id": "gcrta_22",
      "direction_id": 0,
      "file": "route-gcrta_22-dir0.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Lorain",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 22 - Outbound"
    },
    {
      "route_id": "gcrta_22",
      "direction_id": 1,
      "file": "route-gcrta_22-dir1.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Lorain",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 22 - Inbound"
    },
    {
      "route_id": "gcrta_25",
      "direction_id": 0,
      "file": "route-gcrta_25-dir0.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Madison\u2013Clark",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 25 - Outbound"
    },
    {
      "route_id": "gcrta_25",
      "direction_id": 1,
      "file": "route-gcrta_25-dir1.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Madison\u2013Clark",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 25 - Inbound"
    },
    {
      "route_id": "gcrta_251",
      "direction_id": 0,
      "file": "route-gcrta_251-dir0.json",
      "route_type": "3",
      "route_short_name": "251",
      "route_long_name": "Strongsville Park-N-Ride",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 251 - Outbound"
    },
    {
      "route_id": "gcrta_251",
      "direction_id": 1,
      "file": "route-gcrta_251-dir1.json",
      "route_type": "3",
      "route_short_name": "251",
      "route_long_name": "Strongsville Park-N-Ride",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 251 - Inbound"
    },
    {
      "route_id": "gcrta_26",
      "direction_id": 0,
      "file": "route-gcrta_26-dir0.json",
      "route_type": "3",
      "route_short_name": "26-26A",
      "route_long_name": "Detroit",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 26-26A - Outbound"
    },
    {
      "route_id": "gcrta_26",
      "direction_id": 1,
      "file": "route-gcrta_26-dir1.json",
      "route_type": "3",
      "route_short_name": "26-26A",
      "route_long_name": "Detroit",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 26-26A - Inbound"
    },
    {
      "route_id": "gcrta_28",
      "direction_id": 0,
      "file": "route-gcrta_28-dir0.json",
      "route_type": "3",
      "route_short_name": "28-28A",
      "route_long_name": "Euclid",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 28-28A - Outbound"
    },
    {
      "route_id": "gcrta_28",
      "direction_id": 1,
      "file": "route-gcrta_28-dir1.json",
      "route_type": "3",
      "route_short_name": "28-28A",
      "route_long_name": "Euclid",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 28-28A - Inbound"
    },
    {
      "route_id": "gcrta_3",
      "direction_id": 0,
      "file": "route-gcrta_3-dir0.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Superior",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 3 - Outbound"
    },
    {
      "route_id": "gcrta_3",
      "direction_id": 1,
      "file": "route-gcrta_3-dir1.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Superior",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 3 - Inbound"
    },
    {
      "route_id": "gcrta_31",
      "direction_id": 0,
      "file": "route-gcrta_31-dir0.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "St. Clair\u2013Babbitt",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 31 - Outbound"
    },
    {
      "route_id": "gcrta_31",
      "direction_id": 1,
      "file": "route-gcrta_31-dir1.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "St. Clair\u2013Babbitt",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 31 - Inbound"
    },
    {
      "route_id": "gcrta_34",
      "direction_id": 0,
      "file": "route-gcrta_34-dir0.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "East 200\u2013Green",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 34 - Outbound"
    },
    {
      "route_id": "gcrta_34",
      "direction_id": 1,
      "file": "route-gcrta_34-dir1.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "East 200\u2013Green",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 34 - Inbound"
    },
    {
      "route_id": "gcrta_35",
      "direction_id": 0,
      "file": "route-gcrta_35-dir0.json",
      "route_type": "3",
      "route_short_name": "35",
      "route_long_name": "Lee Blvd.\u2013East 123",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 35 - Outbound"
    },
    {
      "route_id": "gcrta_35",
      "direction_id": 1,
      "file": "route-gcrta_35-dir1.json",
      "route_type": "3",
      "route_short_name": "35",
      "route_long_name": "Lee Blvd.\u2013East 123",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 35 - Inbound"
    },
    {
      "route_id": "gcrta_37",
      "direction_id": 0,
      "file": "route-gcrta_37-dir0.json",
      "route_type": "3",
      "route_short_name": "37",
      "route_long_name": "Hayden\u2013East 185",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 37 - Outbound"
    },
    {
      "route_id": "gcrta_37",
      "direction_id": 1,
      "file": "route-gcrta_37-dir1.json",
      "route_type": "3",
      "route_short_name": "37",
      "route_long_name": "Hayden\u2013East 185",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 37 - Inbound"
    },
    {
      "route_id": "gcrta_39",
      "direction_id": 0,
      "file": "route-gcrta_39-dir0.json",
      "route_type": "3",
      "route_short_name": "39",
      "route_long_name": "Lakeshore",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 39 - Outbound"
    },
    {
      "route_id": "gcrta_39",
      "direction_id": 1,
      "file": "route-gcrta_39-dir1.json",
      "route_type": "3",
      "route_short_name": "39",
      "route_long_name": "Lakeshore",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 39 - Inbound"
    },
    {
      "route_id": "gcrta_40",
      "direction_id": 0,
      "file": "route-gcrta_40-dir0.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Lakeview\u2013Lee",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 40 - Outbound"
    },
    {
      "route_id": "gcrta_40",
      "direction_id": 1,
      "file": "route-gcrta_40-dir1.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Lakeview\u2013Lee",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 40 - Inbound"
    },
    {
      "route_id": "gcrta_41",
      "direction_id": 0,
      "file": "route-gcrta_41-dir0.json",
      "route_type": "3",
      "route_short_name": "41-41F",
      "route_long_name": "Warrensville",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 41-41F - Outbound"
    },
    {
      "route_id": "gcrta_41",
      "direction_id": 1,
      "file": "route-gcrta_41-dir1.json",
      "route_type": "3",
      "route_short_name": "41-41F",
      "route_long_name": "Warrensville",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 41-41F - Inbound"
    },
    {
      "route_id": "gcrta_45",
      "direction_id": 0,
      "file": "route-gcrta_45-dir0.json",
      "route_type": "3",
      "route_short_name": "45",
      "route_long_name": "Ridge\u2013Fulton",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 45 - Outbound"
    },
    {
      "route_id": "gcrta_45",
      "direction_id": 1,
      "file": "route-gcrta_45-dir1.json",
      "route_type": "3",
      "route_short_name": "45",
      "route_long_name": "Ridge\u2013Fulton",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 45 - Inbound"
    },
    {
      "route_id": "gcrta_48",
      "direction_id": 0,
      "file": "route-gcrta_48-dir0.json",
      "route_type": "3",
      "route_short_name": "48",
      "route_long_name": "East 131",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 48 - Outbound"
    },
    {
      "route_id": "gcrta_48",
      "direction_id": 1,
      "file": "route-gcrta_48-dir1.json",
      "route_type": "3",
      "route_short_name": "48",
      "route_long_name": "East 131",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 48 - Inbound"
    },
    {
      "route_id": "gcrta_50",
      "direction_id": 0,
      "file": "route-gcrta_50-dir0.json",
      "route_type": "3",
      "route_short_name": "50",
      "route_long_name": "East 116",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 50 - Outbound"
    },
    {
      "route_id": "gcrta_50",
      "direction_id": 1,
      "file": "route-gcrta_50-dir1.json",
      "route_type": "3",
      "route_short_name": "50",
      "route_long_name": "East 116",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 50 - Inbound"
    },
    {
      "route_id": "gcrta_51",
      "direction_id": 0,
      "file": "route-gcrta_51-dir0.json",
      "route_type": "3",
      "route_short_name": "51-51A",
      "route_long_name": "MetroHealth Line",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 51-51A - Outbound"
    },
    {
      "route_id": "gcrta_51",
      "direction_id": 1,
      "file": "route-gcrta_51-dir1.json",
      "route_type": "3",
      "route_short_name": "51-51A",
      "route_long_name": "MetroHealth Line",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 51-51A - Inbound"
    },
    {
      "route_id": "gcrta_53",
      "direction_id": 0,
      "file": "route-gcrta_53-dir0.json",
      "route_type": "3",
      "route_short_name": "53-53A",
      "route_long_name": "MetroHealth Line\u2013Broadview",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 53-53A - Outbound"
    },
    {
      "route_id": "gcrta_53",
      "direction_id": 1,
      "file": "route-gcrta_53-dir1.json",
      "route_type": "3",
      "route_short_name": "53-53A",
      "route_long_name": "MetroHealth Line\u2013Broadview",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 53-53A - Inbound"
    },
    {
      "route_id": "gcrta_54",
      "direction_id": 0,
      "file": "route-gcrta_54-dir0.json",
      "route_type": "3",
      "route_short_name": "54",
      "route_long_name": "Brookpark\u2013Rockside",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 54 - Outbound"
    },
    {
      "route_id": "gcrta_54",
      "direction_id": 1,
      "file": "route-gcrta_54-dir1.json",
      "route_type": "3",
      "route_short_name": "54",
      "route_long_name": "Brookpark\u2013Rockside",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 54 - Inbound"
    },
    {
      "route_id": "gcrta_55",
      "direction_id": 0,
      "file": "route-gcrta_55-dir0.json",
      "route_type": "3",
      "route_short_name": "55-55B-55C",
      "route_long_name": "Clifton",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 55-55B-55C - Outbound"
    },
    {
      "route_id": "gcrta_55",
      "direction_id": 1,
      "file": "route-gcrta_55-dir1.json",
      "route_type": "3",
      "route_short_name": "55-55B-55C",
      "route_long_name": "Clifton",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 55-55B-55C - Inbound"
    },
    {
      "route_id": "gcrta_6",
      "direction_id": 0,
      "file": "route-gcrta_6-dir0.json",
      "route_type": "3",
      "route_short_name": "HL",
      "route_long_name": "HealthLine",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route HL - Outbound"
    },
    {
      "route_id": "gcrta_6",
      "direction_id": 1,
      "file": "route-gcrta_6-dir1.json",
      "route_type": "3",
      "route_short_name": "HL",
      "route_long_name": "HealthLine",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route HL - Inbound"
    },
    {
      "route_id": "gcrta_62",
      "direction_id": 0,
      "file": "route-gcrta_62-dir0.json",
      "route_type": "3",
      "route_short_name": "nan",
      "route_long_name": "B-Line Trolley",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route nan - Outbound"
    },
    {
      "route_id": "gcrta_62",
      "direction_id": 1,
      "file": "route-gcrta_62-dir1.json",
      "route_type": "3",
      "route_short_name": "nan",
      "route_long_name": "B-Line Trolley",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route nan - Inbound"
    },
    {
      "route_id": "gcrta_66",
      "direction_id": 0,
      "file": "route-gcrta_66-dir0.json",
      "route_type": "1",
      "route_short_name": "RL",
      "route_long_name": "Red Line",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route RL - Outbound"
    },
    {
      "route_id": "gcrta_66",
      "direction_id": 1,
      "file": "route-gcrta_66-dir1.json",
      "route_type": "1",
      "route_short_name": "RL",
      "route_long_name": "Red Line",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route RL - Inbound"
    },
    {
      "route_id": "gcrta_67R",
      "direction_id": 0,
      "file": "route-gcrta_67R-dir0.json",
      "route_type": "3",
      "route_short_name": "67R",
      "route_long_name": "Blue Line Replacement Bus",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 67R - Outbound"
    },
    {
      "route_id": "gcrta_67R",
      "direction_id": 1,
      "file": "route-gcrta_67R-dir1.json",
      "route_type": "3",
      "route_short_name": "67R",
      "route_long_name": "Blue Line Replacement Bus",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 67R - Inbound"
    },
    {
      "route_id": "gcrta_68R",
      "direction_id": 0,
      "file": "route-gcrta_68R-dir0.json",
      "route_type": "3",
      "route_short_name": "68R",
      "route_long_name": "Green Line Replacement Bus",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 68R - Outbound"
    },
    {
      "route_id": "gcrta_68R",
      "direction_id": 1,
      "file": "route-gcrta_68R-dir1.json",
      "route_type": "3",
      "route_short_name": "68R",
      "route_long_name": "Green Line Replacement Bus",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 68R - Inbound"
    },
    {
      "route_id": "gcrta_7",
      "direction_id": 0,
      "file": "route-gcrta_7-dir0.json",
      "route_type": "3",
      "route_short_name": "7-7A",
      "route_long_name": "Monticello",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 7-7A - Outbound"
    },
    {
      "route_id": "gcrta_7",
      "direction_id": 1,
      "file": "route-gcrta_7-dir1.json",
      "route_type": "3",
      "route_short_name": "7-7A",
      "route_long_name": "Monticello",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 7-7A - Inbound"
    },
    {
      "route_id": "gcrta_71",
      "direction_id": 0,
      "file": "route-gcrta_71-dir0.json",
      "route_type": "3",
      "route_short_name": "71",
      "route_long_name": "Pearl\u2013Tiedeman",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 71 - Outbound"
    },
    {
      "route_id": "gcrta_71",
      "direction_id": 1,
      "file": "route-gcrta_71-dir1.json",
      "route_type": "3",
      "route_short_name": "71",
      "route_long_name": "Pearl\u2013Tiedeman",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 71 - Inbound"
    },
    {
      "route_id": "gcrta_77",
      "direction_id": 0,
      "file": "route-gcrta_77-dir0.json",
      "route_type": "3",
      "route_short_name": "77",
      "route_long_name": "Brecksville",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 77 - Outbound"
    },
    {
      "route_id": "gcrta_77",
      "direction_id": 1,
      "file": "route-gcrta_77-dir1.json",
      "route_type": "3",
      "route_short_name": "77",
      "route_long_name": "Brecksville",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 77 - Inbound"
    },
    {
      "route_id": "gcrta_78",
      "direction_id": 0,
      "file": "route-gcrta_78-dir0.json",
      "route_type": "3",
      "route_short_name": "78",
      "route_long_name": "West 117\u2013Puritas",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 78 - Outbound"
    },
    {
      "route_id": "gcrta_78",
      "direction_id": 1,
      "file": "route-gcrta_78-dir1.json",
      "route_type": "3",
      "route_short_name": "78",
      "route_long_name": "West 117\u2013Puritas",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 78 - Inbound"
    },
    {
      "route_id": "gcrta_8",
      "direction_id": 0,
      "file": "route-gcrta_8-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Cedar\u2013Buckeye",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 8 - Outbound"
    },
    {
      "route_id": "gcrta_8",
      "direction_id": 1,
      "file": "route-gcrta_8-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Cedar\u2013Buckeye",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 8 - Inbound"
    },
    {
      "route_id": "gcrta_83",
      "direction_id": 0,
      "file": "route-gcrta_83-dir0.json",
      "route_type": "3",
      "route_short_name": "83",
      "route_long_name": "Warren\u2013West 130",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 83 - Outbound"
    },
    {
      "route_id": "gcrta_83",
      "direction_id": 1,
      "file": "route-gcrta_83-dir1.json",
      "route_type": "3",
      "route_short_name": "83",
      "route_long_name": "Warren\u2013West 130",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 83 - Inbound"
    },
    {
      "route_id": "gcrta_86",
      "direction_id": 0,
      "file": "route-gcrta_86-dir0.json",
      "route_type": "3",
      "route_short_name": "86",
      "route_long_name": "Rocky River Dr.\u2013Bagley",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 86 - Outbound"
    },
    {
      "route_id": "gcrta_86",
      "direction_id": 1,
      "file": "route-gcrta_86-dir1.json",
      "route_type": "3",
      "route_short_name": "86",
      "route_long_name": "Rocky River Dr.\u2013Bagley",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 86 - Inbound"
    },
    {
      "route_id": "gcrta_9",
      "direction_id": 0,
      "file": "route-gcrta_9-dir0.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "Mayfield\u2013Hough",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 9 - Outbound"
    },
    {
      "route_id": "gcrta_9",
      "direction_id": 1,
      "file": "route-gcrta_9-dir1.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "Mayfield\u2013Hough",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 9 - Inbound"
    },
    {
      "route_id": "gcrta_90",
      "direction_id": 0,
      "file": "route-gcrta_90-dir0.json",
      "route_type": "3",
      "route_short_name": "90",
      "route_long_name": "Broadway\u2013Libby",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 90 - Outbound"
    },
    {
      "route_id": "gcrta_90",
      "direction_id": 1,
      "file": "route-gcrta_90-dir1.json",
      "route_type": "3",
      "route_short_name": "90",
      "route_long_name": "Broadway\u2013Libby",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 90 - Inbound"
    },
    {
      "route_id": "gcrta_94",
      "direction_id": 0,
      "file": "route-gcrta_94-dir0.json",
      "route_type": "3",
      "route_short_name": "94",
      "route_long_name": "East 260\u2013Richmond",
      "agency_id": "GCRTA",
      "direction_name": "Outbound",
      "route_title": "Route 94 - Outbound"
    },
    {
      "route_id": "gcrta_94",
      "direction_id": 1,
      "file": "route-gcrta_94-dir1.json",
      "route_type": "3",
      "route_short_name": "94",
      "route_long_name": "East 260\u2013Richmond",
      "agency_id": "GCRTA",
      "direction_name": "Inbound",
      "route_title": "Route 94 - Inbound"
    },
    {
      "route_id": "laketran_1",
      "direction_id": 0,
      "file": "route-laketran_1-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Mentor - Painesville",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 1 - Outbound"
    },
    {
      "route_id": "laketran_1",
      "direction_id": 1,
      "file": "route-laketran_1-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "Mentor - Painesville",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 1 - Inbound"
    },
    {
      "route_id": "laketran_10",
      "direction_id": 0,
      "file": "route-laketran_10-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Mentor Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 10 - Outbound"
    },
    {
      "route_id": "laketran_10",
      "direction_id": 1,
      "file": "route-laketran_10-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Mentor Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 10 - Inbound"
    },
    {
      "route_id": "laketran_11",
      "direction_id": 0,
      "file": "route-laketran_11-dir0.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Madison/Lakeland Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 11 - Outbound"
    },
    {
      "route_id": "laketran_11",
      "direction_id": 1,
      "file": "route-laketran_11-dir1.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "Madison/Lakeland Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 11 - Inbound"
    },
    {
      "route_id": "laketran_12",
      "direction_id": 0,
      "file": "route-laketran_12-dir0.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Eastlake/Wickliffe Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 12 - Outbound"
    },
    {
      "route_id": "laketran_12",
      "direction_id": 1,
      "file": "route-laketran_12-dir1.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Eastlake/Wickliffe Park-n-Ride",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 12 - Inbound"
    },
    {
      "route_id": "laketran_13",
      "direction_id": 0,
      "file": "route-laketran_13-dir0.json",
      "route_type": "3",
      "route_short_name": "13",
      "route_long_name": "Painesville-Mentor-Wickliffe-University Circle",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 13 - Outbound"
    },
    {
      "route_id": "laketran_13",
      "direction_id": 1,
      "file": "route-laketran_13-dir1.json",
      "route_type": "3",
      "route_short_name": "13",
      "route_long_name": "Painesville-Mentor-Wickliffe-University Circle",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 13 - Inbound"
    },
    {
      "route_id": "laketran_14",
      "direction_id": 0,
      "file": "route-laketran_14-dir0.json",
      "route_type": "3",
      "route_short_name": "14",
      "route_long_name": "Lake Erie College",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 14 - Outbound"
    },
    {
      "route_id": "laketran_14",
      "direction_id": 1,
      "file": "route-laketran_14-dir1.json",
      "route_type": "3",
      "route_short_name": "14",
      "route_long_name": "Lake Erie College",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 14 - Inbound"
    },
    {
      "route_id": "laketran_2",
      "direction_id": 0,
      "file": "route-laketran_2-dir0.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Mentor - Euclid",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 2 - Outbound"
    },
    {
      "route_id": "laketran_2",
      "direction_id": 1,
      "file": "route-laketran_2-dir1.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Mentor - Euclid",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 2 - Inbound"
    },
    {
      "route_id": "laketran_3",
      "direction_id": 0,
      "file": "route-laketran_3-dir0.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Mentor - Shoregate",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 3 - Outbound"
    },
    {
      "route_id": "laketran_3",
      "direction_id": 1,
      "file": "route-laketran_3-dir1.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Mentor - Shoregate",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 3 - Inbound"
    },
    {
      "route_id": "laketran_4",
      "direction_id": 0,
      "file": "route-laketran_4-dir0.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "Painesville - Madison",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 4 - Outbound"
    },
    {
      "route_id": "laketran_4",
      "direction_id": 1,
      "file": "route-laketran_4-dir1.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "Painesville - Madison",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 4 - Inbound"
    },
    {
      "route_id": "laketran_5",
      "direction_id": 0,
      "file": "route-laketran_5-dir0.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Painesville - Fairport",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 5 - Outbound"
    },
    {
      "route_id": "laketran_5",
      "direction_id": 1,
      "file": "route-laketran_5-dir1.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "Painesville - Fairport",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 5 - Inbound"
    },
    {
      "route_id": "laketran_6",
      "direction_id": 0,
      "file": "route-laketran_6-dir0.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "Mentor - Willoughby Hills",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 6 - Outbound"
    },
    {
      "route_id": "laketran_6",
      "direction_id": 1,
      "file": "route-laketran_6-dir1.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "Mentor - Willoughby Hills",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 6 - Inbound"
    },
    {
      "route_id": "laketran_7",
      "direction_id": 0,
      "file": "route-laketran_7-dir0.json",
      "route_type": "3",
      "route_short_name": "7",
      "route_long_name": "Campus Loop",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 7 - Outbound"
    },
    {
      "route_id": "laketran_8",
      "direction_id": 0,
      "file": "route-laketran_8-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Mentor-Mentor on the Lake",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 8 - Outbound"
    },
    {
      "route_id": "laketran_8",
      "direction_id": 1,
      "file": "route-laketran_8-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Mentor-Mentor on the Lake",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 8 - Inbound"
    },
    {
      "route_id": "laketran_9",
      "direction_id": 0,
      "file": "route-laketran_9-dir0.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "Painesville-Mentor",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Outbound",
      "route_title": "Route 9 - Outbound"
    },
    {
      "route_id": "laketran_9",
      "direction_id": 1,
      "file": "route-laketran_9-dir1.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "Painesville-Mentor",
      "agency_id": "75aa82bb-da99-4d25-924a-cf04b02f4983",
      "direction_name": "Inbound",
      "route_title": "Route 9 - Inbound"
    },
    {
      "route_id": "metro_1-30",
      "direction_id": 0,
      "file": "route-metro_1-30-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "W. Market / Montrose",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 1 - Outbound"
    },
    {
      "route_id": "metro_1-30",
      "direction_id": 1,
      "file": "route-metro_1-30-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "W. Market / Montrose",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 1 - Inbound"
    },
    {
      "route_id": "metro_10-30",
      "direction_id": 0,
      "file": "route-metro_10-30-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Howard / Portage Trl. / ITC",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 10 - Outbound"
    },
    {
      "route_id": "metro_10-30",
      "direction_id": 1,
      "file": "route-metro_10-30-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Howard / Portage Trl. / ITC",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 10 - Inbound"
    },
    {
      "route_id": "metro_13-30",
      "direction_id": 0,
      "file": "route-metro_13-30-dir0.json",
      "route_type": "3",
      "route_short_name": "13",
      "route_long_name": "Grant Ave / Firestone",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 13 - Outbound"
    },
    {
      "route_id": "metro_13-30",
      "direction_id": 1,
      "file": "route-metro_13-30-dir1.json",
      "route_type": "3",
      "route_short_name": "13",
      "route_long_name": "Grant Ave / Firestone",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 13 - Inbound"
    },
    {
      "route_id": "metro_15-30",
      "direction_id": 0,
      "file": "route-metro_15-30-dir0.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Brown / Inman",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 15 - Outbound"
    },
    {
      "route_id": "metro_15-30",
      "direction_id": 1,
      "file": "route-metro_15-30-dir1.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Brown / Inman",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 15 - Inbound"
    },
    {
      "route_id": "metro_16-30",
      "direction_id": 0,
      "file": "route-metro_16-30-dir0.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Euclid Ave / Vernon Odom Blvd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 16 - Outbound"
    },
    {
      "route_id": "metro_16-30",
      "direction_id": 1,
      "file": "route-metro_16-30-dir1.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Euclid Ave / Vernon Odom Blvd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 16 - Inbound"
    },
    {
      "route_id": "metro_19-30",
      "direction_id": 0,
      "file": "route-metro_19-30-dir0.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "E. Exchange / Eastland / ITC",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 19 - Outbound"
    },
    {
      "route_id": "metro_19-30",
      "direction_id": 1,
      "file": "route-metro_19-30-dir1.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "E. Exchange / Eastland / ITC",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 19 - Inbound"
    },
    {
      "route_id": "metro_2-30",
      "direction_id": 0,
      "file": "route-metro_2-30-dir0.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Arlington / Interstate Prkwy",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 2 - Outbound"
    },
    {
      "route_id": "metro_2-30",
      "direction_id": 1,
      "file": "route-metro_2-30-dir1.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "Arlington / Interstate Prkwy",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 2 - Inbound"
    },
    {
      "route_id": "metro_20-30",
      "direction_id": 0,
      "file": "route-metro_20-30-dir0.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Tallmadge Ave / Brimfield Wal Mart",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 20 - Outbound"
    },
    {
      "route_id": "metro_20-30",
      "direction_id": 1,
      "file": "route-metro_20-30-dir1.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Tallmadge Ave / Brimfield Wal Mart",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 20 - Inbound"
    },
    {
      "route_id": "metro_22-32",
      "direction_id": 0,
      "file": "route-metro_22-32-dir0.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Howe Ave / ITC / Stow",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 22 - Outbound"
    },
    {
      "route_id": "metro_22-32",
      "direction_id": 1,
      "file": "route-metro_22-32-dir1.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Howe Ave / ITC / Stow",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 22 - Inbound"
    },
    {
      "route_id": "metro_23-30",
      "direction_id": 0,
      "file": "route-metro_23-30-dir0.json",
      "route_type": "3",
      "route_short_name": "23",
      "route_long_name": "Goodyear Hts. / Gilchrist Rd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 23 - Outbound"
    },
    {
      "route_id": "metro_23-30",
      "direction_id": 1,
      "file": "route-metro_23-30-dir1.json",
      "route_type": "3",
      "route_short_name": "23",
      "route_long_name": "Goodyear Hts. / Gilchrist Rd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 23 - Inbound"
    },
    {
      "route_id": "metro_25-30",
      "direction_id": 0,
      "file": "route-metro_25-30-dir0.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Kelly Ave / Triplett Blvd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 25 - Outbound"
    },
    {
      "route_id": "metro_25-30",
      "direction_id": 1,
      "file": "route-metro_25-30-dir1.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "Kelly Ave / Triplett Blvd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 25 - Inbound"
    },
    {
      "route_id": "metro_26-30",
      "direction_id": 0,
      "file": "route-metro_26-30-dir0.json",
      "route_type": "3",
      "route_short_name": "26",
      "route_long_name": "Delia / White Pond",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 26 - Outbound"
    },
    {
      "route_id": "metro_26-30",
      "direction_id": 1,
      "file": "route-metro_26-30-dir1.json",
      "route_type": "3",
      "route_short_name": "26",
      "route_long_name": "Delia / White Pond",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 26 - Inbound"
    },
    {
      "route_id": "metro_27-30",
      "direction_id": 0,
      "file": "route-metro_27-30-dir0.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "W. Exchange / Merriman Valley",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 27 - Outbound"
    },
    {
      "route_id": "metro_27-30",
      "direction_id": 1,
      "file": "route-metro_27-30-dir1.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "W. Exchange / Merriman Valley",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 27 - Inbound"
    },
    {
      "route_id": "metro_29-30",
      "direction_id": 0,
      "file": "route-metro_29-30-dir0.json",
      "route_type": "3",
      "route_short_name": "29",
      "route_long_name": "S. Main / Manchester Rd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 29 - Outbound"
    },
    {
      "route_id": "metro_29-30",
      "direction_id": 1,
      "file": "route-metro_29-30-dir1.json",
      "route_type": "3",
      "route_short_name": "29",
      "route_long_name": "S. Main / Manchester Rd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 29 - Inbound"
    },
    {
      "route_id": "metro_3-30",
      "direction_id": 0,
      "file": "route-metro_3-30-dir0.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Copley Rd / Barberton",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 3 - Outbound"
    },
    {
      "route_id": "metro_3-30",
      "direction_id": 1,
      "file": "route-metro_3-30-dir1.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "Copley Rd / Barberton",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 3 - Inbound"
    },
    {
      "route_id": "metro_31-30",
      "direction_id": 0,
      "file": "route-metro_31-30-dir0.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Cuyahoga Falls / Macedonia",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 31 - Outbound"
    },
    {
      "route_id": "metro_31-30",
      "direction_id": 1,
      "file": "route-metro_31-30-dir1.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Cuyahoga Falls / Macedonia",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 31 - Inbound"
    },
    {
      "route_id": "metro_32-30",
      "direction_id": 0,
      "file": "route-metro_32-30-dir0.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "Stow-Hudson / Twinsburg",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 32 - Outbound"
    },
    {
      "route_id": "metro_32-30",
      "direction_id": 1,
      "file": "route-metro_32-30-dir1.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "Stow-Hudson / Twinsburg",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 32 - Inbound"
    },
    {
      "route_id": "metro_40-30",
      "direction_id": 0,
      "file": "route-metro_40-30-dir0.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Manchester / W. Thornton Rd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 40 - Outbound"
    },
    {
      "route_id": "metro_40-30",
      "direction_id": 1,
      "file": "route-metro_40-30-dir1.json",
      "route_type": "3",
      "route_short_name": "40",
      "route_long_name": "Manchester / W. Thornton Rd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 40 - Inbound"
    },
    {
      "route_id": "metro_55-30",
      "direction_id": 0,
      "file": "route-metro_55-30-dir0.json",
      "route_type": "3",
      "route_short_name": "55",
      "route_long_name": "U of A Roo Express",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 55 - Outbound"
    },
    {
      "route_id": "metro_55-30",
      "direction_id": 1,
      "file": "route-metro_55-30-dir1.json",
      "route_type": "3",
      "route_short_name": "55",
      "route_long_name": "U of A Roo Express",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 55 - Inbound"
    },
    {
      "route_id": "metro_6-30",
      "direction_id": 0,
      "file": "route-metro_6-30-dir0.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "E. Exchange / Canton Rd",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 6 - Outbound"
    },
    {
      "route_id": "metro_6-30",
      "direction_id": 1,
      "file": "route-metro_6-30-dir1.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "E. Exchange / Canton Rd",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 6 - Inbound"
    },
    {
      "route_id": "metro_600-30",
      "direction_id": 1,
      "file": "route-metro_600-30-dir1.json",
      "route_type": "3",
      "route_short_name": "600",
      "route_long_name": "Late Night Zone",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 600 - Inbound"
    },
    {
      "route_id": "metro_61-30",
      "direction_id": 0,
      "file": "route-metro_61-30-dir0.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "Cleveland / Wade Park",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 61 - Outbound"
    },
    {
      "route_id": "metro_61-30",
      "direction_id": 1,
      "file": "route-metro_61-30-dir1.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "Cleveland / Wade Park",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 61 - Inbound"
    },
    {
      "route_id": "metro_8-30",
      "direction_id": 0,
      "file": "route-metro_8-30-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Barberton",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 8 - Outbound"
    },
    {
      "route_id": "metro_8-30",
      "direction_id": 1,
      "file": "route-metro_8-30-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "Barberton",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 8 - Inbound"
    },
    {
      "route_id": "metro_9-30",
      "direction_id": 0,
      "file": "route-metro_9-30-dir0.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "East Ave / Battles Ave",
      "agency_id": "50010",
      "direction_name": "Outbound",
      "route_title": "Route 9 - Outbound"
    },
    {
      "route_id": "metro_9-30",
      "direction_id": 1,
      "file": "route-metro_9-30-dir1.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "East Ave / Battles Ave",
      "agency_id": "50010",
      "direction_name": "Inbound",
      "route_title": "Route 9 - Inbound"
    }
  ]
};
