window.routesIndex = {
  "version": "20260727-1439",
  "city_id": "columbus",
  "routes": [
    {
      "route_id": "cota_001",
      "direction_id": 0,
      "file": "route-cota_001-dir0.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "KENNY/LIVINGSTON",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 1 - Outbound"
    },
    {
      "route_id": "cota_001",
      "direction_id": 1,
      "file": "route-cota_001-dir1.json",
      "route_type": "3",
      "route_short_name": "1",
      "route_long_name": "KENNY/LIVINGSTON",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 1 - Inbound"
    },
    {
      "route_id": "cota_002",
      "direction_id": 0,
      "file": "route-cota_002-dir0.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "E MAIN/N HIGH",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 2 - Outbound"
    },
    {
      "route_id": "cota_002",
      "direction_id": 1,
      "file": "route-cota_002-dir1.json",
      "route_type": "3",
      "route_short_name": "2",
      "route_long_name": "E MAIN/N HIGH",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 2 - Inbound"
    },
    {
      "route_id": "cota_003",
      "direction_id": 0,
      "file": "route-cota_003-dir0.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "NORTHWEST/HARRISBURG",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 3 - Outbound"
    },
    {
      "route_id": "cota_003",
      "direction_id": 1,
      "file": "route-cota_003-dir1.json",
      "route_type": "3",
      "route_short_name": "3",
      "route_long_name": "NORTHWEST/HARRISBURG",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 3 - Inbound"
    },
    {
      "route_id": "cota_004",
      "direction_id": 0,
      "file": "route-cota_004-dir0.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "INDIANOLA/LOCKBOURNE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 4 - Outbound"
    },
    {
      "route_id": "cota_004",
      "direction_id": 1,
      "file": "route-cota_004-dir1.json",
      "route_type": "3",
      "route_short_name": "4",
      "route_long_name": "INDIANOLA/LOCKBOURNE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 4 - Inbound"
    },
    {
      "route_id": "cota_005",
      "direction_id": 0,
      "file": "route-cota_005-dir0.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "W 5TH AVE/REFUGEE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 5 - Outbound"
    },
    {
      "route_id": "cota_005",
      "direction_id": 1,
      "file": "route-cota_005-dir1.json",
      "route_type": "3",
      "route_short_name": "5",
      "route_long_name": "W 5TH AVE/REFUGEE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 5 - Inbound"
    },
    {
      "route_id": "cota_006",
      "direction_id": 0,
      "file": "route-cota_006-dir0.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "SULLIVANT",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 6 - Outbound"
    },
    {
      "route_id": "cota_006",
      "direction_id": 1,
      "file": "route-cota_006-dir1.json",
      "route_type": "3",
      "route_short_name": "6",
      "route_long_name": "SULLIVANT",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 6 - Inbound"
    },
    {
      "route_id": "cota_007",
      "direction_id": 0,
      "file": "route-cota_007-dir0.json",
      "route_type": "3",
      "route_short_name": "7",
      "route_long_name": "MT VERNON",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 7 - Outbound"
    },
    {
      "route_id": "cota_007",
      "direction_id": 1,
      "file": "route-cota_007-dir1.json",
      "route_type": "3",
      "route_short_name": "7",
      "route_long_name": "MT VERNON",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 7 - Inbound"
    },
    {
      "route_id": "cota_008",
      "direction_id": 0,
      "file": "route-cota_008-dir0.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "KARL/S HIGH/PARSONS",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 8 - Outbound"
    },
    {
      "route_id": "cota_008",
      "direction_id": 1,
      "file": "route-cota_008-dir1.json",
      "route_type": "3",
      "route_short_name": "8",
      "route_long_name": "KARL/S HIGH/PARSONS",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 8 - Inbound"
    },
    {
      "route_id": "cota_009",
      "direction_id": 0,
      "file": "route-cota_009-dir0.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "W MOUND/BRENTNELL",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 9 - Outbound"
    },
    {
      "route_id": "cota_009",
      "direction_id": 1,
      "file": "route-cota_009-dir1.json",
      "route_type": "3",
      "route_short_name": "9",
      "route_long_name": "W MOUND/BRENTNELL",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 9 - Inbound"
    },
    {
      "route_id": "cota_010",
      "direction_id": 0,
      "file": "route-cota_010-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "E BROAD/W BROAD",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 10 - Outbound"
    },
    {
      "route_id": "cota_010",
      "direction_id": 1,
      "file": "route-cota_010-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "E BROAD/W BROAD",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 10 - Inbound"
    },
    {
      "route_id": "cota_011",
      "direction_id": 0,
      "file": "route-cota_011-dir0.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "BRYDEN/MAIZE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 11 - Outbound"
    },
    {
      "route_id": "cota_011",
      "direction_id": 1,
      "file": "route-cota_011-dir1.json",
      "route_type": "3",
      "route_short_name": "11",
      "route_long_name": "BRYDEN/MAIZE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 11 - Inbound"
    },
    {
      "route_id": "cota_012",
      "direction_id": 0,
      "file": "route-cota_012-dir0.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "MCKINLEY/FIELDS",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 12 - Outbound"
    },
    {
      "route_id": "cota_012",
      "direction_id": 1,
      "file": "route-cota_012-dir1.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "MCKINLEY/FIELDS",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 12 - Inbound"
    },
    {
      "route_id": "cota_021",
      "direction_id": 0,
      "file": "route-cota_021-dir0.json",
      "route_type": "3",
      "route_short_name": "21",
      "route_long_name": "HILLIARD ROME",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 21 - Outbound"
    },
    {
      "route_id": "cota_021",
      "direction_id": 1,
      "file": "route-cota_021-dir1.json",
      "route_type": "3",
      "route_short_name": "21",
      "route_long_name": "HILLIARD ROME",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 21 - Inbound"
    },
    {
      "route_id": "cota_022",
      "direction_id": 0,
      "file": "route-cota_022-dir0.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "OSU-RICKENBACKER",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 22 - Outbound"
    },
    {
      "route_id": "cota_022",
      "direction_id": 1,
      "file": "route-cota_022-dir1.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "OSU-RICKENBACKER",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 22 - Inbound"
    },
    {
      "route_id": "cota_023",
      "direction_id": 0,
      "file": "route-cota_023-dir0.json",
      "route_type": "3",
      "route_short_name": "23",
      "route_long_name": "JAMES-STELZER",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 23 - Outbound"
    },
    {
      "route_id": "cota_023",
      "direction_id": 1,
      "file": "route-cota_023-dir1.json",
      "route_type": "3",
      "route_short_name": "23",
      "route_long_name": "JAMES-STELZER",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 23 - Inbound"
    },
    {
      "route_id": "cota_024",
      "direction_id": 0,
      "file": "route-cota_024-dir0.json",
      "route_type": "3",
      "route_short_name": "24",
      "route_long_name": "HAMILTON RD",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 24 - Outbound"
    },
    {
      "route_id": "cota_024",
      "direction_id": 1,
      "file": "route-cota_024-dir1.json",
      "route_type": "3",
      "route_short_name": "24",
      "route_long_name": "HAMILTON RD",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 24 - Inbound"
    },
    {
      "route_id": "cota_025",
      "direction_id": 0,
      "file": "route-cota_025-dir0.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "BRICE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 25 - Outbound"
    },
    {
      "route_id": "cota_025",
      "direction_id": 1,
      "file": "route-cota_025-dir1.json",
      "route_type": "3",
      "route_short_name": "25",
      "route_long_name": "BRICE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 25 - Inbound"
    },
    {
      "route_id": "cota_031",
      "direction_id": 0,
      "file": "route-cota_031-dir0.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "HUDSON",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 31 - Outbound"
    },
    {
      "route_id": "cota_031",
      "direction_id": 1,
      "file": "route-cota_031-dir1.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "HUDSON",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 31 - Inbound"
    },
    {
      "route_id": "cota_032",
      "direction_id": 0,
      "file": "route-cota_032-dir0.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "N BROADWAY",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 32 - Outbound"
    },
    {
      "route_id": "cota_032",
      "direction_id": 1,
      "file": "route-cota_032-dir1.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "N BROADWAY",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 32 - Inbound"
    },
    {
      "route_id": "cota_033",
      "direction_id": 0,
      "file": "route-cota_033-dir0.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "HENDERSON",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 33 - Outbound"
    },
    {
      "route_id": "cota_033",
      "direction_id": 1,
      "file": "route-cota_033-dir1.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "HENDERSON",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 33 - Inbound"
    },
    {
      "route_id": "cota_034",
      "direction_id": 0,
      "file": "route-cota_034-dir0.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "MORSE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 34 - Outbound"
    },
    {
      "route_id": "cota_034",
      "direction_id": 1,
      "file": "route-cota_034-dir1.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "MORSE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 34 - Inbound"
    },
    {
      "route_id": "cota_035",
      "direction_id": 0,
      "file": "route-cota_035-dir0.json",
      "route_type": "3",
      "route_short_name": "35",
      "route_long_name": "DUBLIN-GRANVILLE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 35 - Outbound"
    },
    {
      "route_id": "cota_035",
      "direction_id": 1,
      "file": "route-cota_035-dir1.json",
      "route_type": "3",
      "route_short_name": "35",
      "route_long_name": "DUBLIN-GRANVILLE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 35 - Inbound"
    },
    {
      "route_id": "cota_041",
      "direction_id": 0,
      "file": "route-cota_041-dir0.json",
      "route_type": "3",
      "route_short_name": "41",
      "route_long_name": "CROSSWOODS-POLARIS",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 41 - Outbound"
    },
    {
      "route_id": "cota_041",
      "direction_id": 1,
      "file": "route-cota_041-dir1.json",
      "route_type": "3",
      "route_short_name": "41",
      "route_long_name": "CROSSWOODS-POLARIS",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 41 - Inbound"
    },
    {
      "route_id": "cota_042",
      "direction_id": 0,
      "file": "route-cota_042-dir0.json",
      "route_type": "3",
      "route_short_name": "42",
      "route_long_name": "SHARON WOODS",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 42 - Outbound"
    },
    {
      "route_id": "cota_042",
      "direction_id": 1,
      "file": "route-cota_042-dir1.json",
      "route_type": "3",
      "route_short_name": "42",
      "route_long_name": "SHARON WOODS",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 42 - Inbound"
    },
    {
      "route_id": "cota_043",
      "direction_id": 0,
      "file": "route-cota_043-dir0.json",
      "route_type": "3",
      "route_short_name": "43",
      "route_long_name": "WESTERVILLE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 43 - Outbound"
    },
    {
      "route_id": "cota_043",
      "direction_id": 1,
      "file": "route-cota_043-dir1.json",
      "route_type": "3",
      "route_short_name": "43",
      "route_long_name": "WESTERVILLE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 43 - Inbound"
    },
    {
      "route_id": "cota_044",
      "direction_id": 0,
      "file": "route-cota_044-dir0.json",
      "route_type": "3",
      "route_short_name": "44",
      "route_long_name": "EASTON",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 44 - Outbound"
    },
    {
      "route_id": "cota_044",
      "direction_id": 1,
      "file": "route-cota_044-dir1.json",
      "route_type": "3",
      "route_short_name": "44",
      "route_long_name": "EASTON",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 44 - Inbound"
    },
    {
      "route_id": "cota_045",
      "direction_id": 0,
      "file": "route-cota_045-dir0.json",
      "route_type": "3",
      "route_short_name": "45",
      "route_long_name": "NEW ALBANY",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 45 - Outbound"
    },
    {
      "route_id": "cota_045",
      "direction_id": 1,
      "file": "route-cota_045-dir1.json",
      "route_type": "3",
      "route_short_name": "45",
      "route_long_name": "NEW ALBANY",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 45 - Inbound"
    },
    {
      "route_id": "cota_046",
      "direction_id": 0,
      "file": "route-cota_046-dir0.json",
      "route_type": "3",
      "route_short_name": "46",
      "route_long_name": "GAHANNA",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 46 - Outbound"
    },
    {
      "route_id": "cota_046",
      "direction_id": 1,
      "file": "route-cota_046-dir1.json",
      "route_type": "3",
      "route_short_name": "46",
      "route_long_name": "GAHANNA",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 46 - Inbound"
    },
    {
      "route_id": "cota_051",
      "direction_id": 0,
      "file": "route-cota_051-dir0.json",
      "route_type": "3",
      "route_short_name": "51",
      "route_long_name": "REYNOLDSBURG",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 51 - Outbound"
    },
    {
      "route_id": "cota_051",
      "direction_id": 1,
      "file": "route-cota_051-dir1.json",
      "route_type": "3",
      "route_short_name": "51",
      "route_long_name": "REYNOLDSBURG",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 51 - Inbound"
    },
    {
      "route_id": "cota_052",
      "direction_id": 0,
      "file": "route-cota_052-dir0.json",
      "route_type": "3",
      "route_short_name": "52",
      "route_long_name": "CANAL WINCHESTER",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 52 - Outbound"
    },
    {
      "route_id": "cota_052",
      "direction_id": 1,
      "file": "route-cota_052-dir1.json",
      "route_type": "3",
      "route_short_name": "52",
      "route_long_name": "CANAL WINCHESTER",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 52 - Inbound"
    },
    {
      "route_id": "cota_061",
      "direction_id": 0,
      "file": "route-cota_061-dir0.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "GROVE CITY",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 61 - Outbound"
    },
    {
      "route_id": "cota_061",
      "direction_id": 1,
      "file": "route-cota_061-dir1.json",
      "route_type": "3",
      "route_short_name": "61",
      "route_long_name": "GROVE CITY",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 61 - Inbound"
    },
    {
      "route_id": "cota_071",
      "direction_id": 0,
      "file": "route-cota_071-dir0.json",
      "route_type": "3",
      "route_short_name": "71",
      "route_long_name": "HILLIARD",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 71 - Outbound"
    },
    {
      "route_id": "cota_071",
      "direction_id": 1,
      "file": "route-cota_071-dir1.json",
      "route_type": "3",
      "route_short_name": "71",
      "route_long_name": "HILLIARD",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 71 - Inbound"
    },
    {
      "route_id": "cota_072",
      "direction_id": 0,
      "file": "route-cota_072-dir0.json",
      "route_type": "3",
      "route_short_name": "72",
      "route_long_name": "TUTTLE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 72 - Outbound"
    },
    {
      "route_id": "cota_072",
      "direction_id": 1,
      "file": "route-cota_072-dir1.json",
      "route_type": "3",
      "route_short_name": "72",
      "route_long_name": "TUTTLE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 72 - Inbound"
    },
    {
      "route_id": "cota_073",
      "direction_id": 0,
      "file": "route-cota_073-dir0.json",
      "route_type": "3",
      "route_short_name": "73",
      "route_long_name": "DUBLIN",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 73 - Outbound"
    },
    {
      "route_id": "cota_073",
      "direction_id": 1,
      "file": "route-cota_073-dir1.json",
      "route_type": "3",
      "route_short_name": "73",
      "route_long_name": "DUBLIN",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 73 - Inbound"
    },
    {
      "route_id": "cota_074",
      "direction_id": 0,
      "file": "route-cota_074-dir0.json",
      "route_type": "3",
      "route_short_name": "74",
      "route_long_name": "SMOKY ROW",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 74 - Outbound"
    },
    {
      "route_id": "cota_074",
      "direction_id": 1,
      "file": "route-cota_074-dir1.json",
      "route_type": "3",
      "route_short_name": "74",
      "route_long_name": "SMOKY ROW",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 74 - Inbound"
    },
    {
      "route_id": "cota_075",
      "direction_id": 0,
      "file": "route-cota_075-dir0.json",
      "route_type": "3",
      "route_short_name": "75",
      "route_long_name": "ARLINGTON/1ST AVE",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 75 - Outbound"
    },
    {
      "route_id": "cota_075",
      "direction_id": 1,
      "file": "route-cota_075-dir1.json",
      "route_type": "3",
      "route_short_name": "75",
      "route_long_name": "ARLINGTON/1ST AVE",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 75 - Inbound"
    },
    {
      "route_id": "cota_101",
      "direction_id": 0,
      "file": "route-cota_101-dir0.json",
      "route_type": "3",
      "route_short_name": "CMAX",
      "route_long_name": "CMAX",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route CMAX - Outbound"
    },
    {
      "route_id": "cota_101",
      "direction_id": 1,
      "file": "route-cota_101-dir1.json",
      "route_type": "3",
      "route_short_name": "CMAX",
      "route_long_name": "CMAX",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route CMAX - Inbound"
    },
    {
      "route_id": "cota_102",
      "direction_id": 0,
      "file": "route-cota_102-dir0.json",
      "route_type": "3",
      "route_short_name": "102",
      "route_long_name": "POLARIS PKWY/N HIGH",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route 102 - Outbound"
    },
    {
      "route_id": "cota_102",
      "direction_id": 1,
      "file": "route-cota_102-dir1.json",
      "route_type": "3",
      "route_short_name": "102",
      "route_long_name": "POLARIS PKWY/N HIGH",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route 102 - Inbound"
    },
    {
      "route_id": "cota_141",
      "direction_id": 0,
      "file": "route-cota_141-dir0.json",
      "route_type": "3",
      "route_short_name": "ZOO",
      "route_long_name": "COLUMBUS ZOO",
      "agency_id": "COTA",
      "direction_name": "Outbound",
      "route_title": "Route ZOO - Outbound"
    },
    {
      "route_id": "cota_141",
      "direction_id": 1,
      "file": "route-cota_141-dir1.json",
      "route_type": "3",
      "route_short_name": "ZOO",
      "route_long_name": "COLUMBUS ZOO",
      "agency_id": "COTA",
      "direction_name": "Inbound",
      "route_title": "Route ZOO - Inbound"
    }
  ]
};
