/**
 * MetroFeed Routes Index
 * 
 * This file contains all route lists (bus and rail) for each city.
 * Generated by Python scripts - DO NOT EDIT MANUALLY
 * 
 * Format:
 * - Each city has busRoutes and railRoutes arrays
 * - Each route has: id, label, dir0, dir1
 * - Rail routes can also have: className (for styling)
 */

const ROUTES = {
  portland: {
    busRoutes: [
      // Example structure - replace with actual Portland routes from your Python script
      { id: '1', label: '1 – Vermont', dir0: 'To Hayhurst and Maplewood via Vermont', dir1: 'To Portland City Center' },
      { id: '4', label: '4 – Fessenden', dir0: 'To St Johns', dir1: 'To Portland City Center' }
      // ... add all Portland bus routes here
    ],
    railRoutes: [
      // Example structure - replace with actual Portland rail routes
      { id: '90', label: 'MAX Red Line', className: 'red-line', dir0: 'To Portland International Airport', dir1: 'To Hillsboro' },
      { id: '100', label: 'MAX Blue Line', className: 'blue-line', dir0: 'To Gresham', dir1: 'To Hillsboro' }
      // ... add all Portland rail routes here
    ]
  },
  louisville: {
    busRoutes: [
      // Example structure - replace with actual Louisville routes from your Python script
      { id: '2', label: 'Route 2', dir0: 'Direction 0', dir1: 'Direction 1' },
      { id: '4', label: 'Route 4', dir0: 'Direction 0', dir1: 'Direction 1' }
      // ... add all Louisville bus routes here
    ],
    railRoutes: [] // Louisville has no rail routes
  }
};

/**
 * Get routes for the current city
 * @param {string} cityId - Optional city ID, defaults to auto-detect
 * @returns {Object} Object with busRoutes and railRoutes arrays
 */
function getCityRoutes(cityId) {
  cityId = cityId || getCityIdFromPath();
  const routes = ROUTES[cityId];
  
  if (!routes) {
    console.warn(`[getCityRoutes] Routes for city "${cityId}" not found, returning empty arrays`);
    return { busRoutes: [], railRoutes: [] };
  }
  
  return routes;
}

// Export for use in template
window.ROUTES = ROUTES;
window.getCityRoutes = getCityRoutes;

