window.routesIndex = {
  "version": "20260607-1123",
  "city_id": "toledo",
  "routes": [
    {
      "route_id": "tarta_0200",
      "direction_id": 0,
      "file": "route-tarta_0200-dir0.json",
      "route_type": "3",
      "route_short_name": "02",
      "route_long_name": "Promedica or Oregon via Downtown",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 02 - Outbound"
    },
    {
      "route_id": "tarta_0200",
      "direction_id": 1,
      "file": "route-tarta_0200-dir1.json",
      "route_type": "3",
      "route_short_name": "02",
      "route_long_name": "Promedica or Oregon via Downtown",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 02 - Inbound"
    },
    {
      "route_id": "tarta_0300",
      "direction_id": 0,
      "file": "route-tarta_0300-dir0.json",
      "route_type": "3",
      "route_short_name": "03",
      "route_long_name": "Franklin Park Mall or UTMC via Byrne/Secor",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 03 - Outbound"
    },
    {
      "route_id": "tarta_0300",
      "direction_id": 1,
      "file": "route-tarta_0300-dir1.json",
      "route_type": "3",
      "route_short_name": "03",
      "route_long_name": "Franklin Park Mall or UTMC via Byrne/Secor",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 03 - Inbound"
    },
    {
      "route_id": "tarta_0500",
      "direction_id": 0,
      "file": "route-tarta_0500-dir0.json",
      "route_type": "3",
      "route_short_name": "05",
      "route_long_name": "Flower Hospital or UT Transit via Dorr St",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 05 - Outbound"
    },
    {
      "route_id": "tarta_0500",
      "direction_id": 1,
      "file": "route-tarta_0500-dir1.json",
      "route_type": "3",
      "route_short_name": "05",
      "route_long_name": "Flower Hospital or UT Transit via Dorr St",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 05 - Inbound"
    },
    {
      "route_id": "tarta_1000",
      "direction_id": 0,
      "file": "route-tarta_1000-dir0.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Amazon Rossford via Oak/Glenwood",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 10 - Outbound"
    },
    {
      "route_id": "tarta_1000",
      "direction_id": 1,
      "file": "route-tarta_1000-dir1.json",
      "route_type": "3",
      "route_short_name": "10",
      "route_long_name": "Amazon Rossford via Oak/Glenwood",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 10 - Inbound"
    },
    {
      "route_id": "tarta_1200",
      "direction_id": 0,
      "file": "route-tarta_1200-dir0.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Hollywood Casino via Front/E Broadway",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 12 - Outbound"
    },
    {
      "route_id": "tarta_1200",
      "direction_id": 1,
      "file": "route-tarta_1200-dir1.json",
      "route_type": "3",
      "route_short_name": "12",
      "route_long_name": "Hollywood Casino via Front/E Broadway",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 12 - Inbound"
    },
    {
      "route_id": "tarta_1500",
      "direction_id": 0,
      "file": "route-tarta_1500-dir0.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Meijer Alexis via Summit",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 15 - Outbound"
    },
    {
      "route_id": "tarta_1500",
      "direction_id": 1,
      "file": "route-tarta_1500-dir1.json",
      "route_type": "3",
      "route_short_name": "15",
      "route_long_name": "Meijer Alexis via Summit",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 15 - Inbound"
    },
    {
      "route_id": "tarta_1600",
      "direction_id": 0,
      "file": "route-tarta_1600-dir0.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Meijer Alexis via Manhattan",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 16 - Outbound"
    },
    {
      "route_id": "tarta_1600",
      "direction_id": 1,
      "file": "route-tarta_1600-dir1.json",
      "route_type": "3",
      "route_short_name": "16",
      "route_long_name": "Meijer Alexis via Manhattan",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 16 - Inbound"
    },
    {
      "route_id": "tarta_1700",
      "direction_id": 0,
      "file": "route-tarta_1700-dir0.json",
      "route_type": "3",
      "route_short_name": "17",
      "route_long_name": "Franklin Park Mall via Lagrange/Laskey",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 17 - Outbound"
    },
    {
      "route_id": "tarta_1700",
      "direction_id": 1,
      "file": "route-tarta_1700-dir1.json",
      "route_type": "3",
      "route_short_name": "17",
      "route_long_name": "Franklin Park Mall via Lagrange/Laskey",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 17 - Inbound"
    },
    {
      "route_id": "tarta_1800",
      "direction_id": 0,
      "file": "route-tarta_1800-dir0.json",
      "route_type": "3",
      "route_short_name": "18",
      "route_long_name": "Meijer Alexis via Franklin/Alexis",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 18 - Outbound"
    },
    {
      "route_id": "tarta_1800",
      "direction_id": 1,
      "file": "route-tarta_1800-dir1.json",
      "route_type": "3",
      "route_short_name": "18",
      "route_long_name": "Meijer Alexis via Franklin/Alexis",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 18 - Inbound"
    },
    {
      "route_id": "tarta_1900",
      "direction_id": 0,
      "file": "route-tarta_1900-dir0.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "Franklin Park Mall via Cherry/Sylvania Ave",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 19 - Outbound"
    },
    {
      "route_id": "tarta_1900",
      "direction_id": 1,
      "file": "route-tarta_1900-dir1.json",
      "route_type": "3",
      "route_short_name": "19",
      "route_long_name": "Franklin Park Mall via Cherry/Sylvania Ave",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 19 - Inbound"
    },
    {
      "route_id": "tarta_2000",
      "direction_id": 0,
      "file": "route-tarta_2000-dir0.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Meijer Central via Central/Collingwood",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 20 - Outbound"
    },
    {
      "route_id": "tarta_2000",
      "direction_id": 1,
      "file": "route-tarta_2000-dir1.json",
      "route_type": "3",
      "route_short_name": "20",
      "route_long_name": "Meijer Central via Central/Collingwood",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 20 - Inbound"
    },
    {
      "route_id": "tarta_2200",
      "direction_id": 0,
      "file": "route-tarta_2200-dir0.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Franklin Park Mall via Bancroft",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 22 - Outbound"
    },
    {
      "route_id": "tarta_2200",
      "direction_id": 1,
      "file": "route-tarta_2200-dir1.json",
      "route_type": "3",
      "route_short_name": "22",
      "route_long_name": "Franklin Park Mall via Bancroft",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 22 - Inbound"
    },
    {
      "route_id": "tarta_2600",
      "direction_id": 0,
      "file": "route-tarta_2600-dir0.json",
      "route_type": "3",
      "route_short_name": "26",
      "route_long_name": "Miracle Mile via Lewis",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 26 - Outbound"
    },
    {
      "route_id": "tarta_2600",
      "direction_id": 1,
      "file": "route-tarta_2600-dir1.json",
      "route_type": "3",
      "route_short_name": "26",
      "route_long_name": "Miracle Mile via Lewis",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 26 - Inbound"
    },
    {
      "route_id": "tarta_2700",
      "direction_id": 0,
      "file": "route-tarta_2700-dir0.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "Walmart Central via Nebraska/Reynolds",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 27 - Outbound"
    },
    {
      "route_id": "tarta_2700",
      "direction_id": 1,
      "file": "route-tarta_2700-dir1.json",
      "route_type": "3",
      "route_short_name": "27",
      "route_long_name": "Walmart Central via Nebraska/Reynolds",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 27 - Inbound"
    },
    {
      "route_id": "tarta_3100",
      "direction_id": 0,
      "file": "route-tarta_3100-dir0.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Maumee via Broadway/Glendale/Indian Wood Circle",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 31 - Outbound"
    },
    {
      "route_id": "tarta_3100",
      "direction_id": 1,
      "file": "route-tarta_3100-dir1.json",
      "route_type": "3",
      "route_short_name": "31",
      "route_long_name": "Maumee via Broadway/Glendale/Indian Wood Circle",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 31 - Inbound"
    },
    {
      "route_id": "tarta_3200",
      "direction_id": 0,
      "file": "route-tarta_3200-dir0.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "Holland/Spring Meadows via South/Airport",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 32 - Outbound"
    },
    {
      "route_id": "tarta_3200",
      "direction_id": 1,
      "file": "route-tarta_3200-dir1.json",
      "route_type": "3",
      "route_short_name": "32",
      "route_long_name": "Holland/Spring Meadows via South/Airport",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 32 - Inbound"
    },
    {
      "route_id": "tarta_3300",
      "direction_id": 0,
      "file": "route-tarta_3300-dir0.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "UTMC via Indiana/Detroit/Glendale",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 33 - Outbound"
    },
    {
      "route_id": "tarta_3300",
      "direction_id": 1,
      "file": "route-tarta_3300-dir1.json",
      "route_type": "3",
      "route_short_name": "33",
      "route_long_name": "UTMC via Indiana/Detroit/Glendale",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 33 - Inbound"
    },
    {
      "route_id": "tarta_3400",
      "direction_id": 0,
      "file": "route-tarta_3400-dir0.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "Southwyck via Western/Detroit/Heatherdowns",
      "agency_id": "1",
      "direction_name": "Outbound",
      "route_title": "Route 34 - Outbound"
    },
    {
      "route_id": "tarta_3400",
      "direction_id": 1,
      "file": "route-tarta_3400-dir1.json",
      "route_type": "3",
      "route_short_name": "34",
      "route_long_name": "Southwyck via Western/Detroit/Heatherdowns",
      "agency_id": "1",
      "direction_name": "Inbound",
      "route_title": "Route 34 - Inbound"
    }
  ]
};
